# compile_pico_backends.ps1 -- syntax-only compile check for the pico-sdk
# hwAbstraction backends (pico/gpio/hal_gpio_pico.c, pico/adc/hal_adc_pico.c,
# pico/uart/hal_uart_pico.c, pico/time/hal_time_pico.c).
#
# Phase 1a is move-only: these backends are NOT wired into any CMakeLists
# yet, so there is no real build target to compile them through. This
# script stands in for that -- it invokes the same arm-none-eabi-gcc
# SaftyFW's own build uses, with -fsyntax-only, using the DEFINES/INCLUDES/
# FLAGS derived from SaftyFW's own build.ninja for
# src/tasks/relay_owner.c.obj (a real consumer of hardware/gpio.h that also
# happens to pull in hardware/adc.h's include path transitively through the
# same target, so one reference compile command covers both backends --
# mirrors the pattern in compile_esp_backends.ps1). hal_uart_pico.c
# (tasks/uart_owner.h) and hal_time_pico.c (pico/time.h) both resolve
# through the SAME relay_owner.c.obj DEFINES/INCLUDES/FLAGS --
# relay_owner.c itself is one of the SaftyFW.dir target's ordinary
# src/tasks/*.c files, so the target's whole include surface (src/,
# src/tasks/, pico-sdk's hardware_*/pico_* library include dirs including
# pico_time) is present in that one build statement.
#
# Requires an existing firmware/SaftyFW/build/build.ninja + CMakeFiles/
# rules.ninja (run build_saftyfw_host_tests or a normal SaftyFW CMake
# configure/build at least once first -- these are generated by CMake's
# Ninja generator, not checked in).
#
# Usage: powershell -ExecutionPolicy Bypass -File compile_pico_backends.ps1

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..\..")
$BuildDir = Join-Path $RepoRoot "firmware\SaftyFW\build"
$NinjaPath = Join-Path $BuildDir "build.ninja"
$RulesPath = Join-Path $BuildDir "CMakeFiles\rules.ninja"

# SKIP-FAST (2026-09-23): -Fast skips check_00_saftyfw_target_build.ps1, the
# sole producer of build.ninja/CMakeFiles/rules.ninja in this tree -- so
# either file being missing is a direct, expected consequence of -Fast, not
# a defect. Relabeled to SKIP-FAST only when run_all_checks.ps1 actually set
# KILNCTL_CHECKS_FAST (i.e. -Fast is in effect); with the env var unset, a
# missing build.ninja/rules.ninja still means SaftyFW genuinely was never
# configured/built, and this stays a FAIL. Same convention as
# check_embedded_pico_image_fresh.ps1.
if (-not (Test-Path $NinjaPath)) {
    if ($env:KILNCTL_CHECKS_FAST) {
        Write-Host "SKIP-FAST: Missing $NinjaPath -- -Fast skipped the SaftyFW target build that produces it."
        exit 3
    }
    Write-Error "Missing $NinjaPath -- configure/build SaftyFW at least once first (e.g. via CMake+Ninja)."
    exit 1
}
if (-not (Test-Path $RulesPath)) {
    if ($env:KILNCTL_CHECKS_FAST) {
        Write-Host "SKIP-FAST: Missing $RulesPath -- -Fast skipped the SaftyFW target build that produces it."
        exit 3
    }
    Write-Error "Missing $RulesPath -- configure/build SaftyFW at least once first (e.g. via CMake+Ninja)."
    exit 1
}

$ninjaText = Get-Content $NinjaPath -Raw
$rulesText = Get-Content $RulesPath -Raw

# Pull the compiler exe out of the C_COMPILER__SaftyFW_unscanned_Release
# rule (same rule src/tasks/relay_owner.c.obj below is built with).
$ruleMatch = [regex]::Match($rulesText, 'rule C_COMPILER__SaftyFW_unscanned_Release.*?command = [^"]*"([^"]+)"', [System.Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $ruleMatch.Success) {
    Write-Error "Could not find rule C_COMPILER__SaftyFW_unscanned_Release in $RulesPath"
    exit 1
}
$compilerExe = $ruleMatch.Groups[1].Value
if (-not (Test-Path $compilerExe)) {
    Write-Error "Compiler not found at $compilerExe -- no arm-none-eabi toolchain available on this machine; stopping rather than faking a pass."
    exit 1
}

# Pull DEFINES/INCLUDES/FLAGS from the relay_owner.c.obj build statement --
# a real consumer of hardware/gpio.h in the SaftyFW.dir target (the target's
# hardware_adc include path is also present here, since both hardware_gpio
# and hardware_adc are library dependencies of the same SaftyFW target).
$blockMatch = [regex]::Match($ninjaText, 'build CMakeFiles/SaftyFW\.dir/src/tasks/relay_owner\.c\.obj:.*?\r?\n(.*?)\r?\n\r?\n', [System.Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $blockMatch.Success) {
    Write-Error "Could not find the relay_owner.c.obj build statement in $NinjaPath"
    exit 1
}
$block = $blockMatch.Groups[1].Value

function Get-NinjaVar([string]$block, [string]$name) {
    $m = [regex]::Match($block, "(?m)^\s*$name\s*=\s*(.*)$")
    if (-not $m.Success) {
        return ""
    }
    return $m.Groups[1].Value
}

$defines = Get-NinjaVar $block "DEFINES"
$includes = Get-NinjaVar $block "INCLUDES"
$flags = Get-NinjaVar $block "FLAGS"

if (-not $includes) {
    Write-Error "Could not extract INCLUDES from the relay_owner.c.obj build statement"
    exit 1
}

$HalDir = Join-Path $RepoRoot "firmware\hwAbstraction"
$ownIncludes = @(
    "-I" + ((Join-Path $HalDir "interface") -replace '\\', '/')
)

$sources = @(
    (Join-Path $HalDir "pico\gpio\hal_gpio_pico.c"),
    (Join-Path $HalDir "pico\adc\hal_adc_pico.c"),
    (Join-Path $HalDir "pico\uart\hal_uart_pico.c"),
    (Join-Path $HalDir "pico\time\hal_time_pico.c"),
    (Join-Path $HalDir "pico\flash\hal_flash_pico.c"),
    (Join-Path $HalDir "pico\scratch\hal_scratch_pico.c"),
    (Join-Path $HalDir "pico\wdt\hal_wdt_pico.c"),
    (Join-Path $HalDir "pico\spi\hal_spi_pico.c")
)

$failed = $false
# PID-keyed response file. A fixed $env:TEMP name is machine-global, and
# run_all_checks.ps1 runs checks in parallel: two concurrent copies of this
# script rewrite the same .rsp inside the per-source loop. Reproduced at
# A exit=1 B exit=1 with "ld.exe: cannot find @...hal_pico_backend_compile
# .rsp: Invalid argument". The more dangerous shape is silent: one instance
# can read the OTHER instance's .rsp and syntax-check the wrong source while
# still reporting OK for the source it named.
$rspPath = Join-Path $env:TEMP "hal_pico_backend_compile_$PID.rsp"
try {
foreach ($src in $sources) {
    Write-Host "== syntax-checking $src =="
    $srcFwd = $src -replace '\\', '/'
    $rspContent = "$defines $includes $flags $($ownIncludes -join ' ') -fsyntax-only `"$srcFwd`""
    Set-Content -Path $rspPath -Value $rspContent -Encoding ascii -NoNewline
    & $compilerExe "@$rspPath"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAILED: $src" -ForegroundColor Red
        $failed = $true
    } else {
        Write-Host "OK: $src" -ForegroundColor Green
    }
}
} finally {
    Remove-Item -Path $rspPath -Force -ErrorAction SilentlyContinue
}

if ($failed) {
    exit 1
}
Write-Host "All pico hwAbstraction backends passed -fsyntax-only." -ForegroundColor Green
