#!/usr/bin/env python3
"""Tests for the per-task-stack-margin feature's PC-side half: GET_TASK_STATS
decode (:mod:`kilnsim.payloads`) and :mod:`kilnsim.selftest`'s
``task_stack_margins`` check (PASS and FAIL branches). New file, per this
pass's own scope instructions -- does NOT touch
tools/PcTools/tests/test_kilnsim_cli.py.

The reply-decode vector below is transcribed by hand from
firmware/SimFW/test/vectors/cmd_payload_vectors.json's "sys" section
(get_task_stats_two_tasks), the same "hand-derived from PROTOCOL.md, not
generated by calling either production implementation" convention that
manifest documents -- so a bug shared between payloads.py and cmd_task.c
would still show up as a mismatch here.

Run with: python -m unittest discover -s tools/PcTools/tests
"""
from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from kilnsim import payloads, selftest as st  # noqa: E402
from kilnsim.link import MockSimLink  # noqa: E402
from kilnsim.protocol import CommandGroup, SysCmd, TASK_STACK_MARGIN_WARN_THRESHOLD, TaskStatsId  # noqa: E402


# --- decode ------------------------------------------------------------------
class GetTaskStatsDecodeTests(unittest.TestCase):
    def test_encode_request_is_bare_cmd_byte(self):
        wire = payloads.encode_request(CommandGroup.SYS, SysCmd.GET_TASK_STATS)
        self.assertEqual(wire, bytes([0x0A]))

    def test_decode_two_tasks(self):
        # status=OK, task_count=2,
        #   {id=1 (CMD_TASK), allocated=3072 (0x0C00), hwm_free=2500 (0x09C4)}
        #   {id=6 (TELEMETRY), allocated=4096 (0x1000), hwm_free=1000 (0x03E8)}
        wire = bytes.fromhex("000201000cc409060010e803")
        result = payloads.decode_reply(CommandGroup.SYS, SysCmd.GET_TASK_STATS, wire)

        self.assertEqual(result["task_count"], 2)
        self.assertEqual(len(result["tasks"]), 2)

        t0 = result["tasks"][0]
        self.assertEqual(t0["task_stats_id"], TaskStatsId.CMD_TASK)
        self.assertEqual(t0["task_stats_id_name"], "CMD_TASK")
        self.assertEqual(t0["allocated_bytes"], 3072)
        self.assertEqual(t0["hwm_free_bytes"], 2500)
        # peak_used/margin are derived PC-side (PROTOCOL.md sec 4: "the
        # firmware reports the two raw numbers, never a derived ratio").
        self.assertEqual(t0["peak_used_bytes"], 3072 - 2500)
        self.assertAlmostEqual(t0["margin"], 3072 / (3072 - 2500))

        t1 = result["tasks"][1]
        self.assertEqual(t1["task_stats_id"], TaskStatsId.TELEMETRY)
        self.assertEqual(t1["task_stats_id_name"], "TELEMETRY")
        self.assertEqual(t1["allocated_bytes"], 4096)
        self.assertEqual(t1["hwm_free_bytes"], 1000)
        self.assertEqual(t1["peak_used_bytes"], 4096 - 1000)
        self.assertAlmostEqual(t1["margin"], 4096 / (4096 - 1000))

    def test_decode_zero_tasks(self):
        wire = bytes.fromhex("0000")
        result = payloads.decode_reply(CommandGroup.SYS, SysCmd.GET_TASK_STATS, wire)
        self.assertEqual(result["task_count"], 0)
        self.assertEqual(result["tasks"], [])

    def test_decode_unknown_task_stats_id_reports_placeholder_name(self):
        # id=99 (not in TaskStatsId at all -- a wire byte from a future
        # firmware build this Python package's enum hasn't caught up with
        # yet) must decode WITHOUT raising, per PROTOCOL.md sec 4's own
        # SIMFW_TASK_STATS_ID_UNKNOWN reasoning: a reader should still see
        # the record, not have the whole reply fail to decode.
        wire = bytes.fromhex("0001") + bytes.fromhex("6300100010")  # id=99 (0x63), allocated=4096, hwm=4096
        result = payloads.decode_reply(CommandGroup.SYS, SysCmd.GET_TASK_STATS, wire)
        t = result["tasks"][0]
        self.assertEqual(t["task_stats_id"], 99)
        self.assertEqual(t["task_stats_id_name"], "UNKNOWN_99")

    def test_high_water_mark_equal_to_allocated_reports_infinite_margin(self):
        # A task that has NEVER used any of its stack (hwm_free ==
        # allocated, peak_used == 0) must not raise ZeroDivisionError --
        # the whole point of exposing this metric is to run unattended on
        # a bench, so a boundary case in the data must not crash the
        # decoder.
        # id=1, allocated=0x1000 (4096), hwm_free=0x1000 (4096)
        wire = bytes([0x00, 0x01, 0x01]) + (4096).to_bytes(2, "little") + (4096).to_bytes(2, "little")
        result = payloads.decode_reply(CommandGroup.SYS, SysCmd.GET_TASK_STATS, wire)
        t = result["tasks"][0]
        self.assertEqual(t["peak_used_bytes"], 0)
        self.assertEqual(t["margin"], float("inf"))


# --- selftest: task_stack_margins check --------------------------------------
def _task_record(task_stats_id: int, name: str, allocated: int, hwm_free: int) -> dict:
    peak_used = allocated - hwm_free
    margin = (allocated / peak_used) if peak_used > 0 else float("inf")
    return {
        "task_stats_id": task_stats_id,
        "task_stats_id_name": name,
        "allocated_bytes": allocated,
        "hwm_free_bytes": hwm_free,
        "peak_used_bytes": peak_used,
        "margin": margin,
    }


def _script_real_hardware_version(link: MockSimLink) -> None:
    """A fw_git_hash that is neither 'virtual' (virtual_simfw) nor
    '0000000' (MockSimLink's own untouched default) -- the same
    real-hardware-identification convention every other hardware-only
    check in selftest.py already uses (see _classify_expander_link)."""
    link.script_response(CommandGroup.SYS, SysCmd.GET_VERSION, {
        "protocol_version": 1, "min_compatible": 1, "fw_version": "1.2.3",
        "fw_version_major": 1, "fw_version_minor": 2, "fw_version_patch": 3,
        "fw_git_dirty": False, "fw_git_hash": "deadbee",
    })


class TaskStackMarginsCheckTests(unittest.TestCase):
    def setUp(self):
        self.link = MockSimLink()
        self.link.connect()

    def test_not_runnable_against_untouched_mock(self):
        # MockSimLink's own default fw_git_hash is "0000000" -- the check
        # must recognize that and report NOT_RUNNABLE without ever sending
        # GET_TASK_STATS at all, same as every other hardware-dependent
        # check in this module.
        status, detail = st._check_task_stack_margins(self.link)
        self.assertEqual(status, st.STATUS_NOT_RUNNABLE)
        self.assertIn("MockSimLink", detail)

    def test_not_runnable_against_virtual_simfw(self):
        self.link.script_response(CommandGroup.SYS, SysCmd.GET_VERSION, {
            "protocol_version": 1, "min_compatible": 1, "fw_version": "0.0.0",
            "fw_version_major": 0, "fw_version_minor": 0, "fw_version_patch": 0,
            "fw_git_dirty": False, "fw_git_hash": "virtual",
        })
        status, detail = st._check_task_stack_margins(self.link)
        self.assertEqual(status, st.STATUS_NOT_RUNNABLE)
        self.assertIn("virtual_simfw", detail)

    def test_pass_when_every_task_at_or_above_threshold(self):
        _script_real_hardware_version(self.link)
        self.link.script_response(CommandGroup.SYS, SysCmd.GET_TASK_STATS, {
            "task_count": 2,
            "tasks": [
                _task_record(1, "CMD_TASK", 3072, 2500),   # 3072/572 ~= 5.37x
                _task_record(6, "TELEMETRY", 4096, 3000),  # 4096/1096 ~= 3.74x
            ],
        })
        status, detail = st._check_task_stack_margins(self.link)
        self.assertEqual(status, st.STATUS_PASS)
        self.assertIn("2 task(s)", detail)
        self.assertIn(f">= {TASK_STACK_MARGIN_WARN_THRESHOLD:.1f}x", detail)

    def test_fail_when_one_task_under_threshold(self):
        _script_real_hardware_version(self.link)
        # sim_engine's own real historical numbers (2048 B allocated vs. a
        # 2328 B measured worst case -- the incident that actually bricked
        # a board) are impossible to represent with a POSITIVE hwm_free
        # (peak usage exceeded allocation entirely), so this uses a
        # smaller-but-still-real margin instead: 2048 B allocated, only
        # 200 B ever free at the high-water mark -> peak_used 1848 B ->
        # margin 2048/1848 ~= 1.11x, well under the 2x threshold.
        self.link.script_response(CommandGroup.SYS, SysCmd.GET_TASK_STATS, {
            "task_count": 2,
            "tasks": [
                _task_record(3, "SIM_ENGINE", 2048, 200),   # ~1.11x -- FLAGGED
                _task_record(6, "TELEMETRY", 4096, 3000),   # ~3.74x -- fine
            ],
        })
        status, detail = st._check_task_stack_margins(self.link)
        self.assertEqual(status, st.STATUS_FAIL)
        self.assertIn("1/2", detail)
        self.assertIn("SIM_ENGINE", detail)
        self.assertNotIn("TELEMETRY (", detail)  # only the flagged task is named

    def test_fail_when_get_task_stats_reports_zero_tasks(self):
        _script_real_hardware_version(self.link)
        self.link.script_response(CommandGroup.SYS, SysCmd.GET_TASK_STATS, {"task_count": 0, "tasks": []})
        status, detail = st._check_task_stack_margins(self.link)
        self.assertEqual(status, st.STATUS_FAIL)
        self.assertIn("zero tasks", detail)


if __name__ == "__main__":
    unittest.main()
