"""test_config_convert_kiln_package_golden.py -- pins config_convert.py's
kiln_package hash/export logic against bytes the FIRMWARE actually produced.

The old test compared _kiln_pkg_compute_hash() with itself, which can never
catch a wire-format drift between config_convert.py and kiln_package.c's own
canonical hash layout. The fixture tests/fixtures/config_convert/
kiln_package_golden.txt is generated by
firmware/KilnFW/App/test/test_kiln_package.c: it reads the already-committed
zones_cfg_t golden blob (zones_cfg_golden.txt), builds a fixed
kiln_pkg_safety_t with two sentinel pico entries, and runs the real
kiln_package_compute_hash()/kiln_package_export_json() over them. That C test
fails if the committed fixture drifts from what the current firmware produces,
so a firmware wire-format change turns this pair red rather than letting the
Python mirror silently go stale.

This test then recomputes the same hash with
config_convert._kiln_pkg_compute_hash() and checks it against the firmware's
own value, and separately parses the firmware's own exported JSON envelope
(export_json) and runs it through config_convert.convert_kiln_package(),
checking the declared pkg_hash validates and the round-tripped esp_blob_hex
still matches.
"""
import json
import re
from pathlib import Path

import pytest

from kilnctrl import config_convert as cc

GOLDEN = Path(__file__).parent / "fixtures" / "config_convert" / "kiln_package_golden.txt"


def _load_golden():
    meta = {}
    pico = []
    for raw in GOLDEN.read_text(encoding="ascii").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export_json "):
            meta["export_json"] = line[len("export_json "):]
            continue
        m = re.match(r"^pico\[(\d+)\] id=(\d+) type=(\d+) flags=(\d+) value_bits=(\d+)$", line)
        if m:
            pico.append({
                "id": int(m.group(2)),
                "type": int(m.group(3)),
                "flags": int(m.group(4)),
                "value_bits": int(m.group(5)),
            })
            continue
        key, value = line.split(" ", 1)
        if key == "hash":
            meta["hash"] = int(value, 16)
        elif key in ("pkg_schema", "esp_blob_len", "pico_count"):
            meta[key] = int(value)
    return meta, pico


@pytest.fixture(scope="module")
def golden():
    assert GOLDEN.is_file(), f"missing firmware-generated golden {GOLDEN}"
    return _load_golden()


def test_golden_pico_count_matches(golden):
    meta, pico = golden
    assert len(pico) == meta["pico_count"]


def test_python_hash_matches_firmware(golden):
    meta, pico = golden
    doc = json.loads(meta["export_json"])
    esp_blob = bytes.fromhex(doc["esp_blob_hex"])
    assert len(esp_blob) == meta["esp_blob_len"]
    got = cc._kiln_pkg_compute_hash(meta["pkg_schema"], esp_blob, pico)
    assert got == meta["hash"], f"firmware hash 0x{meta['hash']:08x}, python computed 0x{got:08x}"


def test_python_hash_matches_pico_parsed_from_export_json(golden):
    """Same check as above but using the 'pico' list from firmware's own
    exported JSON rather than the golden's separately-parsed pico[] lines --
    catches a drift between kiln_package_export_json()'s pico encoding and
    this golden's own record of what it asked kiln_package_compute_hash()
    to hash."""
    meta, _pico = golden
    doc = json.loads(meta["export_json"])
    esp_blob = bytes.fromhex(doc["esp_blob_hex"])
    got = cc._kiln_pkg_compute_hash(doc["pkg_schema"], esp_blob, doc["pico"])
    assert got == meta["hash"]
    assert doc["pkg_hash"] == f"0x{meta['hash']:08x}"


def test_convert_kiln_package_accepts_firmware_exported_document(golden):
    meta, _pico = golden
    doc = json.loads(meta["export_json"])
    out_doc, report = cc.convert_kiln_package(doc, cc.ZONES_CFG_VERSION)
    assert report.store == "kiln_package"
    assert bytes.fromhex(out_doc["esp_blob_hex"]) == bytes.fromhex(doc["esp_blob_hex"])
    assert out_doc["pico"] == doc["pico"]


def test_convert_document_accepts_firmware_exported_document(golden):
    meta, _pico = golden
    doc = json.loads(meta["export_json"])
    out_doc, report = cc.convert_document(doc, cc.ZONES_CFG_VERSION)
    assert out_doc["kind"] == "kilnctl_kiln_package"
    assert report.store == "kiln_package"
