// cmd_task.c -- see cmd_task.h. Decodes/validates/dispatches every
// delivered benchproto DATA frame (docs/PLAN.md section 5's command-group
// table) and builds the reply usb_owner sends back as that frame's ACK
// (usb_owner_send_reply(), usb_owner.h).
//
// Dispatch is a two-level lookup table -- s_groups[] keyed by
// SIMFW_TASK_ID_* (cmd_ids.h), each entry pointing at its own group's
// cmd_id -> handler table -- so a later agent filling in MODEL/TC/CT/RELAY/
// IO/FAULT's real handlers only ever adds entries to that group's own
// `commands` array; nothing about this file's dispatch *structure* needs to
// change. Today only SYS (s_sys_commands below) has any entries: PING,
// GET_VERSION, GET_CAPS are fully implemented per docs/PROTOCOL.md;
// RESET_SIM/SET_TIMESCALE/SET_SEED are reserved SYS command ids
// (cmd_ids.h) with no table entry, so they fall through to the exact same
// SIMFW_CMD_STATUS_ERR_NOT_IMPL reply every other group's commands get
// today (cmd_task_dispatch()'s fallthrough) -- a clean, defined "not yet
// implemented" answer, never a silently unhandled frame.
#include "cmd_task.h"

#include <string.h>

#include "FreeRTOS.h"
#include "task.h"

#include "benchproto/benchproto_version.h"

#include "build_info.h" // generated by ../../gen_build_info.cmake, see CMakeLists.txt
#include "cmd_ids.h"
#include "task_priorities.h"
#include "usb_owner.h"
#include "version.h"

#define CMD_TASK_STACK_WORDS (configMINIMAL_STACK_SIZE * 2u)

static TaskHandle_t s_task_handle = NULL;
static QueueHandle_t s_inbox = NULL;

// --- Reply payload builder ---------------------------------------------

// Bounds-checked little-endian appender for a reply payload
// (docs/PROTOCOL.md's "multi-byte fields inside command payloads are
// little-endian" convention, BENCHPROTO.md section 3). `overflow` latches
// once any append is refused, so a handler can fire a sequence of rw_*()
// calls without checking each return value individually and still end up
// with a short, safely-truncated payload rather than a buffer overrun --
// every handler below still finishes with *out_len = w.len, so a latched
// overflow is visible in the reply's own length field, not silently hidden.
typedef struct {
    uint8_t *buf;
    uint8_t cap;
    uint8_t len;
    bool overflow;
} reply_writer_t;

static void rw_init(reply_writer_t *w, uint8_t *buf, uint8_t cap)
{
    w->buf = buf;
    w->cap = cap;
    w->len = 0;
    w->overflow = false;
}

static void rw_bytes(reply_writer_t *w, const uint8_t *data, uint8_t n)
{
    if (w->overflow || (uint16_t)w->len + (uint16_t)n > (uint16_t)w->cap) {
        w->overflow = true;
        return;
    }
    memcpy(w->buf + w->len, data, n);
    w->len = (uint8_t)(w->len + n);
}

static void rw_u8(reply_writer_t *w, uint8_t v)
{
    rw_bytes(w, &v, 1);
}

static void rw_u16le(reply_writer_t *w, uint16_t v)
{
    uint8_t b[2] = {(uint8_t)(v & 0xFFu), (uint8_t)((v >> 8) & 0xFFu)};
    rw_bytes(w, b, 2);
}

static void rw_u32le(reply_writer_t *w, uint32_t v)
{
    uint8_t b[4] = {
        (uint8_t)(v & 0xFFu),
        (uint8_t)((v >> 8) & 0xFFu),
        (uint8_t)((v >> 16) & 0xFFu),
        (uint8_t)((v >> 24) & 0xFFu),
    };
    rw_bytes(w, b, 4);
}

// --- SYS group handlers --------------------------------------------------

typedef void (*cmd_handler_fn)(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap);

static void handle_sys_ping(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len, uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

// Shared by GET_VERSION and GET_CAPS -- both start with the same
// version/build-identity block (protocol version + min compatible, this
// firmware's major.minor.patch, dirty flag, git hash) per docs/PROTOCOL.md;
// GET_CAPS appends the capability fields afterward. Factored out so the two
// wire layouts cannot drift apart on this shared prefix.
static void write_version_block(reply_writer_t *w)
{
    rw_u16le(w, (uint16_t)BENCHPROTO_PROTOCOL_VERSION);
    rw_u16le(w, (uint16_t)BENCHPROTO_MIN_COMPATIBLE);
    rw_u8(w, SIMFW_FW_VERSION_MAJOR);
    rw_u8(w, SIMFW_FW_VERSION_MINOR);
    rw_u8(w, SIMFW_FW_VERSION_PATCH);
    rw_u8(w, (uint8_t)SIMFW_FW_GIT_DIRTY);

    size_t hlen = strlen(SIMFW_FW_GIT_COMMIT);
    if (hlen > 255u) {
        hlen = 255u; // can't happen for a real short git hash ("unknown" or ~7-12 hex chars); defensive only
    }
    rw_u8(w, (uint8_t)hlen);
    rw_bytes(w, (const uint8_t *)SIMFW_FW_GIT_COMMIT, (uint8_t)hlen);
}

static void handle_sys_get_version(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                    uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    write_version_block(&w);
    *out_len = w.len;
}

static void handle_sys_get_caps(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    write_version_block(&w);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_MIN);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_MAX);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_DEFAULT);
    rw_u8(&w, SIMFW_CAPS_TC_MAIN_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_TC_SAFETY_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_CT_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_RELAY_CHANNELS);
    rw_u32le(&w, SIMFW_CAPS_FEATURE_BITMASK);
    *out_len = w.len;
}

// Named (not anonymous) so s_sys_commands[] below and cmd_group_t's
// `commands` field (also below) refer to the exact same type -- two
// structurally-identical anonymous struct definitions are still distinct,
// incompatible types in C, which an anonymous version of this pair fails
// to compile with (-Wincompatible-pointer-types) the moment one is
// initialized from a pointer to the other.
typedef struct {
    uint8_t cmd_id;
    cmd_handler_fn handler;
} cmd_table_entry_t;

static const cmd_table_entry_t s_sys_commands[] = {
    {SIMFW_CMD_SYS_PING, handle_sys_ping},
    {SIMFW_CMD_SYS_GET_VERSION, handle_sys_get_version},
    {SIMFW_CMD_SYS_GET_CAPS, handle_sys_get_caps},
};

// --- Dispatch table --------------------------------------------------------

// One row per command group (docs/PLAN.md section 5's table). `commands`/
// `command_count` are NULL/0 for every group but SYS today -- see this
// file's header comment for why that is deliberate and how a later agent
// extends it. Order matches PLAN.md section 5's table top-to-bottom, purely
// for readability; cmd_task_dispatch() below looks up by task_id, not index.
typedef struct {
    uint8_t task_id;
    const cmd_table_entry_t *commands;
    size_t command_count;
} cmd_group_t;

static const cmd_group_t s_groups[] = {
    {SIMFW_TASK_ID_SYS, s_sys_commands, sizeof(s_sys_commands) / sizeof(s_sys_commands[0])},
    {SIMFW_TASK_ID_MODEL, NULL, 0},
    {SIMFW_TASK_ID_TC, NULL, 0},
    {SIMFW_TASK_ID_CT, NULL, 0},
    {SIMFW_TASK_ID_RELAY, NULL, 0},
    {SIMFW_TASK_ID_IO, NULL, 0},
    {SIMFW_TASK_ID_FAULT, NULL, 0},
    {SIMFW_TASK_ID_EVT, NULL, 0},
};
#define CMD_TASK_GROUP_COUNT (sizeof(s_groups) / sizeof(s_groups[0]))

// req->length >= 1 is usb_owner's own delivery precondition
// (usb_owner_handle_deliver() drops length == 0 before ever posting to this
// task's inbox), so payload[0] (the subcommand byte) is always present here.
static void cmd_task_dispatch(const cmd_task_request_t *req, uint8_t *out, uint8_t *out_len)
{
    uint8_t cmd_id = req->payload[0];
    const uint8_t *args = req->payload + 1;
    uint8_t args_len = (uint8_t)(req->length - 1u);

    for (size_t g = 0; g < CMD_TASK_GROUP_COUNT; g++) {
        if (s_groups[g].task_id != req->dst_task) {
            continue;
        }
        for (size_t c = 0; c < s_groups[g].command_count; c++) {
            if (s_groups[g].commands[c].cmd_id == cmd_id) {
                s_groups[g].commands[c].handler(args, args_len, out, out_len, BENCHPROTO_FRAME_MAX_PAYLOAD);
                return;
            }
        }
        // Group exists but this cmd_id has no handler yet -- reserved
        // (e.g. SYS's RESET_SIM/SET_TIMESCALE/SET_SEED) or the whole group
        // is still a stub (MODEL/TC/CT/RELAY/IO/FAULT/EVT). Clean, defined
        // "not yet implemented" answer, not a silent drop.
        out[0] = SIMFW_CMD_STATUS_ERR_NOT_IMPL;
        *out_len = 1;
        return;
    }

    // dst_task matched none of s_groups[] -- shouldn't happen: usb_owner
    // only delivers frames addressed to a task_id it registered
    // (usb_owner_register_task(), called below in cmd_task_start() for
    // every id in s_groups[]), so this is an internal inconsistency, not
    // untrusted wire input. Reported rather than silently dropped so it is
    // visible if it ever does happen (e.g. a future s_groups[] edit that
    // forgets to also register the new id).
    out[0] = SIMFW_CMD_STATUS_ERR_INTERNAL;
    *out_len = 1;
}

static void cmd_task_fn(void *arg)
{
    (void)arg;

    for (;;) {
        cmd_task_request_t req;
        if (xQueueReceive(s_inbox, &req, portMAX_DELAY) != pdTRUE) {
            continue;
        }

        uint8_t reply[BENCHPROTO_FRAME_MAX_PAYLOAD];
        uint8_t reply_len = 0;
        cmd_task_dispatch(&req, reply, &reply_len);

        (void)usb_owner_send_reply(req.dst_task, req.src_device, req.src_task, req.msg_index, reply, reply_len);
    }
}

bool cmd_task_start(void)
{
    s_inbox = xQueueCreate(CMD_TASK_INBOX_DEPTH, sizeof(cmd_task_request_t));
    if (!s_inbox) {
        return false;
    }

    // Register every command group as an addressable task on usb_owner's
    // link (BENCHPROTO.md sec 6) before this function returns -- safe
    // because usb_owner_start() (main.c's existing call, before this one)
    // already initialized the underlying benchproto_link_t synchronously;
    // see usb_owner_start()'s own doc comment.
    for (size_t g = 0; g < CMD_TASK_GROUP_COUNT; g++) {
        if (!usb_owner_register_task(s_groups[g].task_id)) {
            return false;
        }
    }

    BaseType_t ok = xTaskCreate(cmd_task_fn, "cmd_task", CMD_TASK_STACK_WORDS, NULL, SIMFW_PRIO_CMD_TASK,
                                 &s_task_handle);
    if (ok != pdPASS) {
        return false;
    }

    vTaskCoreAffinitySet(s_task_handle, SIMFW_CORE_ELASTIC_PATH);
    return true;
}

QueueHandle_t cmd_task_get_inbox(void)
{
    return s_inbox;
}
