// cmd_task.c -- see cmd_task.h. Decodes/validates/dispatches every
// delivered benchproto DATA frame (docs/DESIGN_NOTES.md section 5's command-group
// table) and builds the reply usb_owner sends back as that frame's ACK
// (usb_owner_send_reply(), usb_owner.h).
//
// Dispatch is a two-level lookup table -- s_groups[] keyed by
// SIMFW_TASK_ID_* (cmd_ids.h), each entry pointing at its own group's
// cmd_id -> handler table -- so a later agent filling in a new group's real
// handlers only ever adds entries to that group's own `commands` array;
// nothing about this file's dispatch *structure* needs to change. Every
// group (SYS/MODEL/TC/CT/RELAY/IO/FAULT) is now fully implemented per
// docs/PROTOCOL.md (gap-closure pass: SYS's RESET_SIM/SET_TIMESCALE/
// SET_SEED/GET_SIM_STATE, FAULT's SET_UNTIL_TRIGGER). Any cmd_id genuinely
// absent from a group's table (a future, not-yet-allocated id) still falls
// through to SIMFW_CMD_STATUS_ERR_NOT_IMPL (cmd_task_dispatch()'s
// fallthrough) -- a clean, defined "not yet implemented" answer, never a
// silently unhandled frame.
#include "cmd_task.h"

#include <string.h>

#include "FreeRTOS.h"
#include "task.h"

#include "benchproto/benchproto_version.h"

#include "build_info.h" // generated by ../../gen_build_info.cmake, see CMakeLists.txt
#include "cmd_ids.h"
#include "task_priorities.h"
#include "usb_owner.h"
#include "version.h"

// MODEL/TC/CT/RELAY/IO/FAULT groups (this pass): each group's handlers call
// only its owning task's public API below -- never another task's private
// state (DESIGN_NOTES.md section 4.5/this file's own header comment). tc_fault_state.h
// and sim_snapshot.h/max31856_regs.h are pulled in as READ-ONLY contracts
// (sim_snapshot_read()/tc_fault_state_read() are documented multi-reader
// APIs; nothing here ever calls the *_write side of either) purely to build
// TC_GET_REGS's shadow-truth reply. spi_emu_a.h/spi_emu_b.h's
// *_get_reg_image()/*_channel_configured() getters close the register-image
// gap a previous pass left open -- see handle_tc_get_regs()'s own comment.
#include "sim_engine.h"
#include "fault_sched.h"
#include "i2c_owner.h"
#include "wave_owner.h"
#include "safe_reboot.h"
#include "spi_emu_a.h"
#include "spi_emu_b.h"
#include "sim/sim_snapshot.h"
#include "sim/tc_fault_state.h"
#include "sim/max31856_regs.h"
#include "sim/fault_engine.h"
#include "sim/thermal_model.h"

#define CMD_TASK_STACK_WORDS (configMINIMAL_STACK_SIZE * 2u)

static TaskHandle_t s_task_handle = NULL;
static QueueHandle_t s_inbox = NULL;

// --- Reply payload builder ---------------------------------------------

// Bounds-checked little-endian appender for a reply payload
// (docs/PROTOCOL.md's "multi-byte fields inside command payloads are
// little-endian" convention, BENCHPROTO.md section 3). `overflow` latches
// once any append is refused, so a handler can fire a sequence of rw_*()
// calls without checking each return value individually and still end up
// with a short, safely-truncated payload rather than a buffer overrun --
// every handler below still finishes with *out_len = w.len, so a latched
// overflow is visible in the reply's own length field, not silently hidden.
typedef struct {
    uint8_t *buf;
    uint8_t cap;
    uint8_t len;
    bool overflow;
} reply_writer_t;

static void rw_init(reply_writer_t *w, uint8_t *buf, uint8_t cap)
{
    w->buf = buf;
    w->cap = cap;
    w->len = 0;
    w->overflow = false;
}

static void rw_bytes(reply_writer_t *w, const uint8_t *data, uint8_t n)
{
    if (w->overflow || (uint16_t)w->len + (uint16_t)n > (uint16_t)w->cap) {
        w->overflow = true;
        return;
    }
    memcpy(w->buf + w->len, data, n);
    w->len = (uint8_t)(w->len + n);
}

static void rw_u8(reply_writer_t *w, uint8_t v)
{
    rw_bytes(w, &v, 1);
}

static void rw_u16le(reply_writer_t *w, uint16_t v)
{
    uint8_t b[2] = {(uint8_t)(v & 0xFFu), (uint8_t)((v >> 8) & 0xFFu)};
    rw_bytes(w, b, 2);
}

static void rw_u32le(reply_writer_t *w, uint32_t v)
{
    uint8_t b[4] = {
        (uint8_t)(v & 0xFFu),
        (uint8_t)((v >> 8) & 0xFFu),
        (uint8_t)((v >> 16) & 0xFFu),
        (uint8_t)((v >> 24) & 0xFFu),
    };
    rw_bytes(w, b, 4);
}

static void rw_u64le(reply_writer_t *w, uint64_t v)
{
    uint8_t b[8];
    for (int i = 0; i < 8; i++) {
        b[i] = (uint8_t)((v >> (8 * i)) & 0xFFu);
    }
    rw_bytes(w, b, 8);
}

static void rw_f32le(reply_writer_t *w, float v)
{
    union {
        float f;
        uint32_t u;
    } conv;
    conv.f = v;
    rw_u32le(w, conv.u);
}

// --- Request payload reader ------------------------------------------------
// Mirror of reply_writer_t for the inbound args[]/args_len this file's
// handlers decode -- same bounds-checked, overflow-latching shape so a
// handler can pull a whole fixed-shape struct off the wire and check
// r.overflow exactly once at the end rather than after every field (docs/
// PROTOCOL.md's "multi-byte fields ... are little-endian" convention).
typedef struct {
    const uint8_t *buf;
    uint8_t len;
    uint8_t pos;
    bool overflow;
} arg_reader_t;

static void ar_init(arg_reader_t *r, const uint8_t *buf, uint8_t len)
{
    r->buf = buf;
    r->len = len;
    r->pos = 0;
    r->overflow = false;
}

static bool ar_bytes(arg_reader_t *r, uint8_t *out, uint8_t n)
{
    if (r->overflow || (uint16_t)r->pos + (uint16_t)n > (uint16_t)r->len) {
        r->overflow = true;
        if (out != NULL) {
            memset(out, 0, n);
        }
        return false;
    }
    memcpy(out, r->buf + r->pos, n);
    r->pos = (uint8_t)(r->pos + n);
    return true;
}

static uint8_t ar_u8(arg_reader_t *r)
{
    uint8_t v = 0;
    ar_bytes(r, &v, 1);
    return v;
}

static uint16_t ar_u16le(arg_reader_t *r)
{
    uint8_t b[2] = {0, 0};
    ar_bytes(r, b, 2);
    return (uint16_t)((uint16_t)b[0] | ((uint16_t)b[1] << 8));
}

static uint32_t ar_u32le(arg_reader_t *r)
{
    uint8_t b[4] = {0, 0, 0, 0};
    ar_bytes(r, b, 4);
    return (uint32_t)b[0] | ((uint32_t)b[1] << 8) | ((uint32_t)b[2] << 16) | ((uint32_t)b[3] << 24);
}

static uint64_t ar_u64le(arg_reader_t *r)
{
    uint8_t b[8] = {0};
    ar_bytes(r, b, 8);
    uint64_t v = 0;
    for (int i = 7; i >= 0; i--) {
        v = (v << 8) | b[i];
    }
    return v;
}

static float ar_f32le(arg_reader_t *r)
{
    union {
        float f;
        uint32_t u;
    } conv;
    conv.u = ar_u32le(r);
    return conv.f;
}

static double ar_f64le(arg_reader_t *r)
{
    union {
        double d;
        uint64_t u;
    } conv;
    conv.u = ar_u64le(r);
    return conv.d;
}

// --- SYS group handlers --------------------------------------------------

typedef void (*cmd_handler_fn)(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap);

static void handle_sys_ping(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len, uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

// Shared by GET_VERSION and GET_CAPS -- both start with the same
// version/build-identity block (protocol version + min compatible, this
// firmware's major.minor.patch, dirty flag, git hash) per docs/PROTOCOL.md;
// GET_CAPS appends the capability fields afterward. Factored out so the two
// wire layouts cannot drift apart on this shared prefix.
static void write_version_block(reply_writer_t *w)
{
    rw_u16le(w, (uint16_t)BENCHPROTO_PROTOCOL_VERSION);
    rw_u16le(w, (uint16_t)BENCHPROTO_MIN_COMPATIBLE);
    rw_u8(w, SIMFW_FW_VERSION_MAJOR);
    rw_u8(w, SIMFW_FW_VERSION_MINOR);
    rw_u8(w, SIMFW_FW_VERSION_PATCH);
    rw_u8(w, (uint8_t)SIMFW_FW_GIT_DIRTY);

    size_t hlen = strlen(SIMFW_FW_GIT_COMMIT);
    if (hlen > 255u) {
        hlen = 255u; // can't happen for a real short git hash ("unknown" or ~7-12 hex chars); defensive only
    }
    rw_u8(w, (uint8_t)hlen);
    rw_bytes(w, (const uint8_t *)SIMFW_FW_GIT_COMMIT, (uint8_t)hlen);
}

static void handle_sys_get_version(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                    uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    write_version_block(&w);
    *out_len = w.len;
}

static void handle_sys_get_caps(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    write_version_block(&w);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_MIN);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_MAX);
    rw_u8(&w, SIMFW_CAPS_ZONE_COUNT_DEFAULT);
    rw_u8(&w, SIMFW_CAPS_TC_MAIN_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_TC_SAFETY_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_CT_CHANNELS);
    rw_u8(&w, SIMFW_CAPS_RELAY_CHANNELS);
    rw_u32le(&w, SIMFW_CAPS_FEATURE_BITMASK);
    *out_len = w.len;
}

// request: {u8 keep_params} -- sim_engine_reset()'s own bool: true = keep
// the current zone params, reinit state from their T0; false = reload the
// last-selected preset first (DESIGN_NOTES.md 6.1's sim_reset tool doc). Queued,
// same as every other MODEL-group setter sim_engine.h documents (this
// function lives in that header's MODEL-group command surface even though
// it is exposed here under SYS, per DESIGN_NOTES.md sec 5's own command-group
// table) -- a false return means the internal command queue was full, not
// a bad argument.
static void handle_sys_reset_sim(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                  uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t keep_params = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, sim_engine_reset(keep_params != 0) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

// request: {u32 timescale_x100} -- sim_engine_set_timescale(), DESIGN_NOTES.md 4.2/
// 5.2's x100 fixed point (1000 == 10.00x, 100 == 1.00x real time, 0 treated
// as 1.00x by sim_engine itself). Queued, same convention as above.
static void handle_sys_set_timescale(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint32_t timescale_x100 = ar_u32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, sim_engine_set_timescale(timescale_x100) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

// request: {u32 seed} -- sim_engine_set_seed(). Queued, same convention as
// above. DESIGN_NOTES.md 4.2's determinism contract ("the same scenario + seed =>
// the same run, byte-for-byte") is why a scenario runner sends this before
// RESET_SIM/the first tick of a fresh run.
static void handle_sys_set_seed(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint32_t seed = ar_u32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, sim_engine_set_seed(seed) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

// request: none. Reply (docs/PROTOCOL.md section 4): {status, u32 seed,
// u8 snapshot_valid, u32 timescale_x100, u64 sim_time_us}. seed comes from
// sim_engine_get_seed() (always available, even before the first tick).
// timescale_x100/sim_time_us come from the published sim_snapshot_t --
// sim_engine.h exposes no standalone timescale getter, but DESIGN_NOTES.md 4.5's
// snapshot already carries timescale_x100/sim_time_us for exactly this kind
// of read, same source telemetry.c's own TELEMETRY frame uses. Before
// sim_engine's first tick, sim_snapshot_read() returns false: snapshot_valid
// is reported 0 and timescale_x100/sim_time_us are reported 0 rather than
// stale/uninitialized values.
static void handle_sys_get_sim_state(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    (void)args;
    (void)args_len;

    uint32_t seed = sim_engine_get_seed();
    sim_snapshot_t snap;
    bool snap_ok = sim_snapshot_read(&snap);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u32le(&w, seed);
    rw_u8(&w, snap_ok ? 1u : 0u);
    rw_u32le(&w, snap_ok ? snap.timescale_x100 : 0u);
    rw_u64le(&w, snap_ok ? snap.sim_time_us : 0u);
    *out_len = w.len;
}

// request: {u32 confirm}. cmd_ids.h's own comment on
// SIMFW_CMD_SYS_REBOOT_BOOTLOADER has the full spec (magic requirement,
// no-reply-on-success convention). safe_reboot_into_bootloader()
// (safe_reboot.h) never returns on success (it jumps into the RP2040's ROM
// USB bootloader after confirming the fixture is in a safe state) -- so
// *out_len is only ever populated on the bad-magic or refusal paths below.
static void handle_sys_reboot_bootloader(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                          uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint32_t confirm = ar_u32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || confirm != SIMFW_CMD_SYS_REBOOT_BOOTLOADER_MAGIC) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    // Reached only on the refusal path -- see safe_reboot.h's "refuse,
    // never reboot anyway" policy for why a timed-out safe-state
    // confirmation is reported back rather than rebooting regardless.
    (void)safe_reboot_into_bootloader();
    rw_u8(&w, SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

// Named (not anonymous) so s_sys_commands[] below and cmd_group_t's
// `commands` field (also below) refer to the exact same type -- two
// structurally-identical anonymous struct definitions are still distinct,
// incompatible types in C, which an anonymous version of this pair fails
// to compile with (-Wincompatible-pointer-types) the moment one is
// initialized from a pointer to the other.
typedef struct {
    uint8_t cmd_id;
    cmd_handler_fn handler;
} cmd_table_entry_t;

static const cmd_table_entry_t s_sys_commands[] = {
    {SIMFW_CMD_SYS_PING, handle_sys_ping},
    {SIMFW_CMD_SYS_GET_VERSION, handle_sys_get_version},
    {SIMFW_CMD_SYS_RESET_SIM, handle_sys_reset_sim},
    {SIMFW_CMD_SYS_SET_TIMESCALE, handle_sys_set_timescale},
    {SIMFW_CMD_SYS_SET_SEED, handle_sys_set_seed},
    {SIMFW_CMD_SYS_GET_CAPS, handle_sys_get_caps},
    {SIMFW_CMD_SYS_GET_SIM_STATE, handle_sys_get_sim_state},
    {SIMFW_CMD_SYS_REBOOT_BOOTLOADER, handle_sys_reboot_bootloader},
};

// --- MODEL group handlers (sim_engine.h) ------------------------------------
// docs/PROTOCOL.md section 5.1. Every setter below is a thin decode-then-call
// wrapper over sim_engine.h's own queue-then-apply-next-tick API -- a false
// return from an owner setter means either an out-of-range zone (sim_engine
// validates against the currently loaded zone_count itself, per its own doc
// comments) or a full command queue; both collapse to ERR_BAD_ARGS/ERR_BUSY
// respectively is not distinguishable from the bool alone, so ERR_BAD_ARGS is
// used for setters (index errors are overwhelmingly the likely cause for a
// well-behaved client) and ERR_BUSY only where a queue-full condition is the
// sole failure mode documented (none of MODEL's setters have another failure
// mode besides "index out of range", so all use ERR_BAD_ARGS).

static void handle_model_set_zone_params(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                          uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t zone = ar_u8(&r);
    thermal_zone_params_t p;
    p.C = ar_f32le(&r);
    p.k_loss = ar_f32le(&r);
    for (uint8_t i = 0; i < THERMAL_MODEL_MAX_ZONES; i++) {
        p.k_couple[i] = ar_f32le(&r);
    }
    p.R_element = ar_f32le(&r);
    p.element_health = ar_f32le(&r);
    p.tc_lag_s = ar_f32le(&r);
    p.T0 = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    if (!sim_engine_set_zone_params(zone, &p)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

static void handle_model_get_zone_params(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                          uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t zone = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    thermal_zone_params_t p;
    if (r.overflow || !sim_engine_get_zone_params(zone, &p)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, zone);
    rw_f32le(&w, p.C);
    rw_f32le(&w, p.k_loss);
    for (uint8_t i = 0; i < THERMAL_MODEL_MAX_ZONES; i++) {
        rw_f32le(&w, p.k_couple[i]);
    }
    rw_f32le(&w, p.R_element);
    rw_f32le(&w, p.element_health);
    rw_f32le(&w, p.tc_lag_s);
    rw_f32le(&w, p.T0);
    *out_len = w.len;
}

static void handle_model_set_ambient(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    float ambient_c = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || !sim_engine_set_ambient(ambient_c)) {
        rw_u8(&w, r.overflow ? SIMFW_CMD_STATUS_ERR_BAD_ARGS : SIMFW_CMD_STATUS_ERR_BUSY);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

static void handle_model_load_preset(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t preset = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || preset >= THERMAL_PRESET_COUNT || !sim_engine_load_preset((thermal_preset_id_t)preset)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

// request: {u8 zone, u8 mode, f32 temp_c} -- mode 0 = return zone to MODEL
// (sim_engine_clear_zone_manual, temp_c ignored), mode 1 = force MANUAL at
// temp_c (sim_engine_force_zone_temp). DESIGN_NOTES.md section 5's "SET_TEMP (force a
// zone temp)" folded together with the clear path so one command id covers
// both halves of sim_engine.h's MANUAL-mode pair.
static void handle_model_set_temp(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                   uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t zone = ar_u8(&r);
    uint8_t mode = ar_u8(&r);
    float temp_c = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    bool ok;
    if (mode == 1u) {
        ok = sim_engine_force_zone_temp(zone, temp_c);
    } else if (mode == 0u) {
        ok = sim_engine_clear_zone_manual(zone);
    } else {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ok ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
    *out_len = w.len;
}

// sim_engine.h has no standalone "set just tc_lag_s" setter -- tc_lag_s is
// one field of thermal_zone_params_t, and the only writer is
// sim_engine_set_zone_params(), which replaces the whole struct. Not an
// owner-API gap: this is a legitimate read-modify-write built entirely from
// two existing public calls (get then set), same pattern a PC-side client
// could do itself with two commands -- folding it into one command id here
// just saves a round trip and avoids a TOCTOU window between a client's own
// get and set.
static void handle_model_set_tc_lag(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                     uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t zone = ar_u8(&r);
    float tc_lag_s = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    thermal_zone_params_t p;
    if (r.overflow || !sim_engine_get_zone_params(zone, &p)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    p.tc_lag_s = tc_lag_s;
    if (!sim_engine_set_zone_params(zone, &p)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BUSY);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

static const cmd_table_entry_t s_model_commands[] = {
    {SIMFW_CMD_MODEL_SET_ZONE_PARAMS, handle_model_set_zone_params},
    {SIMFW_CMD_MODEL_GET_ZONE_PARAMS, handle_model_get_zone_params},
    {SIMFW_CMD_MODEL_SET_AMBIENT, handle_model_set_ambient},
    {SIMFW_CMD_MODEL_LOAD_PRESET, handle_model_load_preset},
    {SIMFW_CMD_MODEL_SET_TEMP, handle_model_set_temp},
    {SIMFW_CMD_MODEL_SET_TC_LAG, handle_model_set_tc_lag},
};

// --- TC group handlers (spi_emu_a.h/spi_emu_b.h + sim_engine.h's MANUAL-mode
// pair + fault_sched.h) ------------------------------------------------------
// docs/PROTOCOL.md section 5.2. Channel numbering matches tc_fault_state.h's
// tc_fault_channel_t: 0..2 = MAIN_0..2 (spi_emu_a, ESP bus), 3 = SAFETY
// (spi_emu_b). MAIN_0..2 index-match zone 0..2 by sim_engine.h's own
// documented zone-to-TC mapping assumption.

// TC_GET_REGS reply layout (docs/PROTOCOL.md section 5.2):
//   byte0      status
//   byte1      channel (echo)
//   byte2      flags: bit0 reg_image_valid, bit1 snapshot_valid (sim_engine
//              has published at least one tick), bit2 stuck_ltcb,
//              bit3 spurious_fault_pin, bit4 force_sr_open,
//              bit5 force_sr_ovuv
//   byte3-18   reg_image[16] -- the channel's live max31856_channel_t.regs[]
//              (MSB-first CR0..SR, MAX31856_REG_* addressing), obtained via
//              spi_emu_a_get_reg_image()/spi_emu_b_get_reg_image(). Only
//              meaningful when flags bit0 (reg_image_valid) is set; zeroed
//              otherwise -- see below.
//   byte19-22  f32 shadow_true_tc_c   -- thermal model's uncorrupted truth
//              (sim_snapshot_t.T_true_c for this channel's zone)
//   byte23-26  f32 shadow_reported_tc_c -- post-TC-lag, pre-corruption signal
//              (T_tc_reported_c / T_safety_reported_c) -- together with
//              byte3-18 (when valid) and byte19-22 this is DESIGN_NOTES.md 5.2's
//              full "the DUT was lied to, this is the truth" pair: the
//              register image the DUT actually reads, plus the shadow
//              truth it was never shown.
//   byte27     dead_mode (max31856_dead_mode_t)
//   byte28-31  f32 noise_sigma_c
//   byte32-35  f32 bit_error_rate
//   byte36-39  u32 spi transactions (spi_emu_a/b_get_stats().transactions)
//   byte40-43  u32 spi protocol_errors
//   byte44-47  u32 spi first_byte_late (TX FIFO underrun count, DESIGN_NOTES.md
//              3.2.1: "counted, never silent")
//
// reg_image_valid semantics: spi_emu_a/b's getters never block (DESIGN_NOTES.md
// 4.5) -- they retry a small, bounded number of times against the PIO
// engine's busy/transaction-counter state (see spi_emu_a.h's coherency-
// guarantee comment) and give up rather than risk a torn image. bit0
// clear means exactly that: the channel was found mid-transaction (CS
// low) across every retry, byte3-18 is all zero, and a client should
// simply ask again -- it is not an error, just a transient "the DUT was
// mid-read/write when you asked" the same as a normal SPI collision would
// produce on real hardware.
static void handle_tc_get_regs(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= TC_FAULT_CHANNEL_COUNT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    sim_snapshot_t snap;
    bool snap_ok = sim_snapshot_read(&snap);

    tc_fault_override_t ovr = {0};
    (void)tc_fault_state_read((tc_fault_channel_t)channel, &ovr);

    max31856_pio_stats_t stats;
    float true_c = 0.0f, reported_c = 0.0f;
    uint8_t reg_image[MAX31856_REG_COUNT] = {0};
    bool reg_image_valid;
    if (channel < TC_FAULT_CHANNEL_SAFETY) {
        stats = spi_emu_a_get_stats(channel);
        reg_image_valid = spi_emu_a_get_reg_image(channel, reg_image);
        if (snap_ok && channel < snap.zone_count) {
            true_c = snap.zones[channel].T_true_c;
            reported_c = snap.zones[channel].T_tc_reported_c;
        }
    } else {
        stats = spi_emu_b_get_stats(0);
        reg_image_valid = spi_emu_b_get_reg_image(0, reg_image);
        if (snap_ok && snap.zone_count > 0) {
            true_c = snap.zones[0].T_true_c;
            reported_c = snap.zones[0].T_safety_reported_c;
        }
    }

    uint8_t flags = 0;
    if (reg_image_valid) flags |= 0x01u;
    if (snap_ok) flags |= 0x02u;
    if (ovr.corruption.stuck_ltcb) flags |= 0x04u;
    if (ovr.corruption.spurious_fault_pin) flags |= 0x08u;
    if (ovr.force_sr_bits & MAX31856_FAULT_OPEN) flags |= 0x10u;
    if (ovr.force_sr_bits & MAX31856_FAULT_OVUV) flags |= 0x20u;

    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, channel);
    rw_u8(&w, flags);
    rw_bytes(&w, reg_image, sizeof(reg_image));
    rw_f32le(&w, true_c);
    rw_f32le(&w, reported_c);
    rw_u8(&w, (uint8_t)ovr.corruption.dead_mode);
    rw_f32le(&w, ovr.corruption.noise_sigma_c);
    rw_f32le(&w, ovr.corruption.bit_error_rate);
    rw_u32le(&w, stats.transactions);
    rw_u32le(&w, stats.protocol_errors);
    rw_u32le(&w, stats.first_byte_late);
    *out_len = w.len;
}

// request: {u8 channel, f32 temp_c}. MAIN_0..2 route to
// sim_engine_force_zone_temp() (keyed by zone index, MAIN channels
// index-match zones 1:1); channel == SAFETY (3) routes to
// sim_engine_force_safety_temp() -- the safety-side MANUAL override, which
// pins T_safety_reported_c independently of every zone's own
// T_true_c/T_tc_reported_c (sim_engine.h's blend/lag+MANUAL safety-TC API),
// so a main-vs-safety disagreement scenario (DESIGN_NOTES.md section 8, test 8) can
// be expressed with either side pinned alone. Any other channel value is out
// of range.
static void handle_tc_force_temp(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                  uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    float temp_c = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= TC_FAULT_CHANNEL_COUNT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    bool ok = (channel == TC_FAULT_CHANNEL_SAFETY) ? sim_engine_force_safety_temp(temp_c)
                                                     : sim_engine_force_zone_temp(channel, temp_c);
    rw_u8(&w, ok ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
    *out_len = w.len;
}

// request: {u8 channel, u8 mode, f32 manual_temp_c} -- mode 0 = MODEL
// (sim_engine_clear_zone_manual() for MAIN, sim_engine_clear_safety_manual()
// for SAFETY), mode 1 = MANUAL at manual_temp_c (sim_engine_force_zone_temp()
// / sim_engine_force_safety_temp()). Same MAIN-vs-SAFETY channel routing as
// handle_tc_force_temp above.
static void handle_tc_set_mode(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    uint8_t mode = ar_u8(&r);
    float temp_c = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= TC_FAULT_CHANNEL_COUNT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    bool is_safety = (channel == TC_FAULT_CHANNEL_SAFETY);
    bool ok;
    if (mode == 1u) {
        ok = is_safety ? sim_engine_force_safety_temp(temp_c) : sim_engine_force_zone_temp(channel, temp_c);
    } else if (mode == 0u) {
        ok = is_safety ? sim_engine_clear_safety_manual() : sim_engine_clear_zone_manual(channel);
    } else {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ok ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
    *out_len = w.len;
}

// request: {u16 slot_id, u8 channel, u8 fault_kind, f32 param0}. fault_kind
// is fault_sched_fault_type_t's TC-only subset (0..5: TC_DISCONNECTED,
// TC_NOISE, TC_STUCK, TC_DEAD_IC, TC_FLAKY_SPI, TC_SPURIOUS_FAULT_PIN).
// Routes through fault_sched_schedule()+fault_sched_fire_now() -- NOT a
// direct tc_fault_state_write() -- because tc_fault_state.h's own header
// documents fault_sched.c as the state's SOLE writer, which "recomputes it
// from scratch every tick from the active fault slot set." A direct write
// from here would be silently clobbered on fault_sched's very next
// evaluation, so a MANUAL-trigger/PERMANENT/ONCE slot fired immediately is
// the only correct way to express "inject this TC fault now" through the
// public API (see fault_sched.h's own note on why this replaces an
// independently-scheduled trigger-eval loop). Reply echoes slot_id so the PC
// side can TC_CLEAR_FAULT it later.
static void handle_tc_inject_fault(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                    uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint16_t slot_id = ar_u16le(&r);
    uint8_t channel = ar_u8(&r);
    uint8_t fault_kind = ar_u8(&r);
    float param0 = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= TC_FAULT_CHANNEL_COUNT || fault_kind > (uint8_t)FAULT_SCHED_TYPE_TC_SPURIOUS_FAULT_PIN) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    fault_trigger_t trigger = {0};
    trigger.kind = FAULT_TRIGGER_MANUAL;
    fault_duration_t duration = {0};
    duration.kind = FAULT_DURATION_PERMANENT;
    fault_repeat_t repeat = {0};
    repeat.kind = FAULT_REPEAT_ONCE;
    float params[4] = {param0, 0.0f, 0.0f, 0.0f};

    uint16_t sid = fault_sched_schedule(slot_id, (fault_sched_fault_type_t)fault_kind, channel, &trigger, &duration,
                                          &repeat, params);
    if (sid == FAULT_ENGINE_INVALID_SLOT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    if (!fault_sched_fire_now(sid)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_INTERNAL);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u16le(&w, sid);
    *out_len = w.len;
}

// request: {u16 slot_id} -- the slot id TC_INJECT_FAULT's reply echoed.
static void handle_tc_clear_fault(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                   uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint16_t slot_id = ar_u16le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || !fault_sched_cancel(slot_id)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

// request: {u8 channel}. Reply (docs/PROTOCOL.md section 5.2):
//   byte0  status
//   byte1  channel (echo)
//   byte2  flags: bit0 configured (spi_emu_a/b_channel_configured() --
//          "has the master EVER written anything to this channel", not
//          just "is it configured correctly" -- DESIGN_NOTES.md 5.2's own framing:
//          a test must be able to tell "configured wrong" apart from
//          "never configured at all"), bit1 reg_image_valid (same
//          busy/retry semantics as TC_GET_REGS's identically-named bit --
//          see that handler's comment)
//   byte3  CR0 (regs[MAX31856_REG_CR0]) -- 0 if reg_image_valid is clear
//   byte4  CR1 (regs[MAX31856_REG_CR1]) -- TC TYPE[3:0] is bits[3:0],
//          AVGSEL[2:0] is bits[6:4] (DESIGN_NOTES.md 3.2's CR1 row); 0 if
//          reg_image_valid is clear
//   byte5  MASK (regs[MAX31856_REG_MASK]) -- 0 if reg_image_valid is clear
// `configured` and `reg_image_valid` are independent: a channel can be
// configured (bit0 set) while a request happens to land mid-transaction
// (bit1 clear, CR0/CR1/MASK all reported as 0) -- callers must check bit1
// before trusting byte3-5, exactly as with TC_GET_REGS, and simply retry
// on a false reg_image_valid rather than treating it as "never
// configured."
static void handle_tc_get_master_config(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                          uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= TC_FAULT_CHANNEL_COUNT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    bool configured;
    uint8_t reg_image[MAX31856_REG_COUNT] = {0};
    bool reg_image_valid;
    if (channel < TC_FAULT_CHANNEL_SAFETY) {
        configured = spi_emu_a_channel_configured(channel);
        reg_image_valid = spi_emu_a_get_reg_image(channel, reg_image);
    } else {
        configured = spi_emu_b_channel_configured(0);
        reg_image_valid = spi_emu_b_get_reg_image(0, reg_image);
    }

    uint8_t flags = 0;
    if (configured) flags |= 0x01u;
    if (reg_image_valid) flags |= 0x02u;

    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, channel);
    rw_u8(&w, flags);
    rw_u8(&w, reg_image[MAX31856_REG_CR0]);
    rw_u8(&w, reg_image[MAX31856_REG_CR1]);
    rw_u8(&w, reg_image[MAX31856_REG_MASK]);
    *out_len = w.len;
}

static const cmd_table_entry_t s_tc_commands[] = {
    {SIMFW_CMD_TC_GET_REGS, handle_tc_get_regs},
    {SIMFW_CMD_TC_FORCE_TEMP, handle_tc_force_temp},
    {SIMFW_CMD_TC_SET_MODE, handle_tc_set_mode},
    {SIMFW_CMD_TC_INJECT_FAULT, handle_tc_inject_fault},
    {SIMFW_CMD_TC_CLEAR_FAULT, handle_tc_clear_fault},
    {SIMFW_CMD_TC_GET_MASTER_CONFIG, handle_tc_get_master_config},
};

// --- CT group handlers (wave_owner.h) ---------------------------------------
// docs/PROTOCOL.md section 5.3. Channel is 0..CT_WAVE_NUM_CHANNELS-1 (3).

static void handle_ct_set_mode(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    uint8_t mode = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= CT_WAVE_NUM_CHANNELS || mode > (uint8_t)CT_WAVE_MODE_MANUAL) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ct_wave_set_mode(channel, (ct_wave_mode_t)mode) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_ct_set_amps(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    float amps = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= CT_WAVE_NUM_CHANNELS) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ct_wave_set_amps(channel, amps) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_ct_set_phase(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    float phase_deg = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= CT_WAVE_NUM_CHANNELS) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ct_wave_set_phase(channel, phase_deg) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

// request: {u8 channel, f32 dc_offset, f32 clip_fraction, u8 dropout_half,
//           u8 dropout_negative_half, u8 apply_immediately}
static void handle_ct_set_distortion(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);
    ct_wave_distortion_t d;
    d.dc_offset = ar_f32le(&r);
    d.clip_fraction = ar_f32le(&r);
    d.dropout_half_cycle = ar_u8(&r) != 0;
    d.dropout_negative_half = ar_u8(&r) != 0;
    d.apply_immediately = ar_u8(&r) != 0;

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || channel >= CT_WAVE_NUM_CHANNELS) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, ct_wave_set_distortion(channel, &d) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_ct_get_state(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t channel = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    ct_wave_channel_state_t st;
    if (r.overflow || channel >= CT_WAVE_NUM_CHANNELS || !ct_wave_get_state(channel, &st)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, (uint8_t)st.mode);
    rw_f32le(&w, st.amps);
    rw_f32le(&w, st.phase_deg);
    rw_f32le(&w, st.distortion.dc_offset);
    rw_f32le(&w, st.distortion.clip_fraction);
    rw_u8(&w, st.distortion.dropout_half_cycle ? 1u : 0u);
    rw_u8(&w, st.distortion.dropout_negative_half ? 1u : 0u);
    rw_u8(&w, st.distortion.apply_immediately ? 1u : 0u);
    rw_f32le(&w, st.last_pwm_scale);
    rw_u8(&w, st.valid ? 1u : 0u);
    *out_len = w.len;
}

static const cmd_table_entry_t s_ct_commands[] = {
    {SIMFW_CMD_CT_SET_MODE, handle_ct_set_mode},
    {SIMFW_CMD_CT_SET_AMPS, handle_ct_set_amps},
    {SIMFW_CMD_CT_SET_DISTORTION, handle_ct_set_distortion},
    {SIMFW_CMD_CT_GET_STATE, handle_ct_get_state},
    {SIMFW_CMD_CT_SET_PHASE, handle_ct_set_phase},
};

// --- RELAY group handlers (i2c_owner.h) -------------------------------------
// docs/PROTOCOL.md section 5.4.

static void handle_relay_get_states(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                     uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    i2c_owner_relay_states_t st = i2c_owner_get_relay_states();

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, st.k1_closed ? 1u : 0u);
    rw_u8(&w, st.k2_closed ? 1u : 0u);
    rw_u8(&w, st.k3_closed ? 1u : 0u);
    rw_u8(&w, st.k5_closed ? 1u : 0u);
    rw_u8(&w, st.k4_closed ? 1u : 0u);
    rw_u8(&w, st.fault_line_asserted ? 1u : 0u);
    rw_u64le(&w, st.sample_time_us);
    rw_u8(&w, st.valid ? 1u : 0u);
    *out_len = w.len;
}

// Max edges returned per RELAY_GET_EDGES reply -- bounded so a full reply
// (status + count + N * 14-byte entries) always fits BENCHPROTO_FRAME_MAX_PAYLOAD
// (128 bytes): 2 + 8*14 = 114.
#define SIMFW_RELAY_EDGES_MAX_PER_REPLY 8u

// request: {u32 since_seq, u8 max_count} -- max_count is clamped to
// SIMFW_RELAY_EDGES_MAX_PER_REPLY server-side; a client that wants more polls
// again with since_seq set to the last entry's seq (i2c_owner.h's own
// pagination contract).
static void handle_relay_get_edges(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                    uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint32_t since_seq = ar_u32le(&r);
    uint8_t max_count = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    if (max_count > SIMFW_RELAY_EDGES_MAX_PER_REPLY) {
        max_count = SIMFW_RELAY_EDGES_MAX_PER_REPLY;
    }

    i2c_owner_relay_edge_t edges[SIMFW_RELAY_EDGES_MAX_PER_REPLY];
    size_t n = i2c_owner_get_relay_edges(edges, max_count, since_seq);

    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, (uint8_t)n);
    for (size_t i = 0; i < n; i++) {
        rw_u32le(&w, edges[i].seq);
        rw_u8(&w, (uint8_t)edges[i].signal);
        rw_u8(&w, edges[i].level ? 1u : 0u);
        rw_u64le(&w, edges[i].time_us);
    }
    *out_len = w.len;
}

static const cmd_table_entry_t s_relay_commands[] = {
    {SIMFW_CMD_RELAY_GET_STATES, handle_relay_get_states},
    {SIMFW_CMD_RELAY_GET_EDGES, handle_relay_get_edges},
};

// --- IO group handlers (i2c_owner.h) ----------------------------------------
// docs/PROTOCOL.md section 5.5.

static void handle_io_set_dir(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                               uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t exp = ar_u8(&r);
    uint8_t pin = ar_u8(&r);
    uint8_t input = ar_u8(&r);
    uint8_t pullup = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || exp > (uint8_t)I2C_OWNER_EXP_2) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    // i2c_owner_io_set_dir() returns false both for a reserved pin (a fixed-
    // role exp1 pin, permanently rejected) and a transiently full command
    // queue -- indistinguishable from this return value alone, so
    // ERR_BAD_ARGS is used (the reserved-pin case is the far more likely
    // cause of a well-behaved client seeing this).
    rw_u8(&w, i2c_owner_io_set_dir((i2c_owner_expander_t)exp, pin, input != 0, pullup != 0) ? SIMFW_CMD_STATUS_OK
                                                                                              : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
    *out_len = w.len;
}

static void handle_io_write(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len, uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t exp = ar_u8(&r);
    uint8_t pin = ar_u8(&r);
    uint8_t level = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || exp > (uint8_t)I2C_OWNER_EXP_2) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, i2c_owner_io_write((i2c_owner_expander_t)exp, pin, level != 0) ? SIMFW_CMD_STATUS_OK
                                                                               : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
    *out_len = w.len;
}

static void handle_io_read(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len, uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t exp = ar_u8(&r);
    uint8_t pin = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || exp > (uint8_t)I2C_OWNER_EXP_2) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    bool level = false;
    i2c_owner_io_read_status_t read_status = I2C_OWNER_IO_READ_OK;
    if (!i2c_owner_io_read((i2c_owner_expander_t)exp, pin, &level, &read_status)) {
        // read_status tells apart a genuinely bad/reserved pin (ERR_BAD_ARGS
        // -- retrying will never help) from "no expander has ever ACKed on
        // this bus yet" (ERR_NO_SAMPLE -- expected and benign on a bench with
        // no MCP23017 attached; see cmd_ids.h's comment on the constant).
        rw_u8(&w, read_status == I2C_OWNER_IO_READ_NO_SAMPLE ? SIMFW_CMD_STATUS_ERR_NO_SAMPLE
                                                              : SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, level ? 1u : 0u);
    *out_len = w.len;
}

static void handle_io_estop_set(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t open = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, i2c_owner_set_estop(open != 0) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_io_estop_get(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, i2c_owner_get_estop_open() ? 1u : 0u);
    *out_len = w.len;
}

static void handle_io_fault_line_get(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                      uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    i2c_owner_relay_states_t st = i2c_owner_get_relay_states();

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, st.fault_line_asserted ? 1u : 0u);
    rw_u64le(&w, st.sample_time_us);
    rw_u8(&w, st.valid ? 1u : 0u);
    *out_len = w.len;
}

static void handle_io_dut_power_set(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                     uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t on = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, i2c_owner_set_dut_power(on != 0) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_io_dut_power_get(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                     uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, i2c_owner_get_dut_power_on() ? 1u : 0u);
    *out_len = w.len;
}

// DUT_POWER_SAFETY_SET/GET (0x09/0x0A) -- relay #2 / J19 / GND_Safty, this
// pass's addition (docs/HARDWARE.md section 3.7 / docs/BOM.md section 6).
// Deliberately separate handlers calling i2c_owner_set/_get_dut_power_safety_on()
// rather than reusing handle_io_dut_power_set/get() with a domain
// parameter -- a shared handler invites a caller to gang both relays behind
// one code path, exactly what two independent relays exist to avoid.
static void handle_io_dut_power_safety_set(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                            uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t on = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, i2c_owner_set_dut_power_safety(on != 0) ? SIMFW_CMD_STATUS_OK : SIMFW_CMD_STATUS_ERR_BUSY);
    *out_len = w.len;
}

static void handle_io_dut_power_safety_get(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                            uint8_t out_cap)
{
    (void)args;
    (void)args_len;
    reply_writer_t w;
    rw_init(&w, out, out_cap);
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u8(&w, i2c_owner_get_dut_power_safety_on() ? 1u : 0u);
    *out_len = w.len;
}

static const cmd_table_entry_t s_io_commands[] = {
    {SIMFW_CMD_IO_SET_DIR, handle_io_set_dir},
    {SIMFW_CMD_IO_WRITE, handle_io_write},
    {SIMFW_CMD_IO_READ, handle_io_read},
    {SIMFW_CMD_IO_ESTOP_SET, handle_io_estop_set},
    {SIMFW_CMD_IO_FAULT_LINE_GET, handle_io_fault_line_get},
    {SIMFW_CMD_IO_DUT_POWER_SET, handle_io_dut_power_set},
    {SIMFW_CMD_IO_ESTOP_GET, handle_io_estop_get},
    {SIMFW_CMD_IO_DUT_POWER_GET, handle_io_dut_power_get},
    {SIMFW_CMD_IO_DUT_POWER_SAFETY_SET, handle_io_dut_power_safety_set},
    {SIMFW_CMD_IO_DUT_POWER_SAFETY_GET, handle_io_dut_power_safety_get},
};

// --- FAULT group handlers (fault_sched.h) -----------------------------------
// docs/PROTOCOL.md section 5.6.

// FAULT_SCHEDULE request layout (docs/PROTOCOL.md section 5.6) -- a compact
// re-encoding of fault_engine.h's fault_trigger_t/fault_duration_t/
// fault_repeat_t (NOT DESIGN_NOTES.md 5.2's original "u8 kind, f32 a, f32 b, u8
// zone/relay" sketch, which predates fault_engine.h and cannot address an
// AFTER_FAULT slot id (needs 16 bits) or carry ON_EVENT's name string at
// all):
//   u16 slot_id
//   u8  fault_type       (fault_sched_fault_type_t, 0..12)
//   u16 target            (zone / tc_fault_channel_t / system-target, per
//                          fault_type -- fault_sched_schedule() itself
//                          validates the pairing)
//   -- trigger --
//   u8  trigger_kind      (fault_trigger_kind_t, 0..6)
//   f64 trigger_a         (AT_SIM_TIME: at_sim_time_s: AT_ZONE_TEMP: temp_c;
//                          ON_RELAY_EDGE/ON_EVENT/AFTER_FAULT: delay_s;
//                          RANDOM_IN: random_t0_s; else unused)
//   f64 trigger_b         (RANDOM_IN: random_t1_s; else unused)
//   u16 trigger_ref        (AT_ZONE_TEMP: zone; ON_RELAY_EDGE: relay;
//                           AFTER_FAULT: after_fault_slot; else unused)
//   u8  trigger_edge        (AT_ZONE_TEMP: temp_edge 0=rising/1=falling;
//                            ON_RELAY_EDGE: relay_edge 0=close/1=open; else 0)
//   char[24] event_name     (ON_EVENT only, NUL-padded ASCII; else ignored)
//   -- duration --
//   u8  duration_kind       (0 PERMANENT, 1 FOR, 2 UNTIL_TRIGGER -- see the
//                            two-frame design below for UNTIL_TRIGGER;
//                            duration_for_s is ignored when duration_kind ==
//                            UNTIL_TRIGGER)
//   f64 duration_for_s
//   -- repeat --
//   u8  repeat_kind          (fault_repeat_kind_t, 0..2)
//   f64 repeat_period_s
//   f64 repeat_jitter_s
//   u16 repeat_n
//   -- params --
//   f32 param0, f32 param1, f32 param2, f32 param3
// Total 93 bytes of args (+1 cmd_id byte), comfortably under the 128-byte
// frame payload cap. Reply: {status, u16 slot_id echo}.
//
// --- UNTIL_TRIGGER two-frame design (gap-closure pass) ----------------------
// fault_duration_t.until_trigger (fault_engine.h) is a second, full
// fault_trigger_t -- "evaluated the same way as a top-level trigger" per
// that header's own doc comment -- the same ~44-byte shape the ARM trigger
// above already spends on the wire. Doubling that inside one FAULT_SCHEDULE
// frame does not fit BENCHPROTO_FRAME_MAX_PAYLOAD (128 bytes: 94 already
// spent on the PERMANENT/FOR case, +44 more = 138) and complicating the wire
// shape to reserve that headroom for every request would tax the common
// (non-UNTIL_TRIGGER) case just to serve the rare one. Instead:
//   1. FAULT_SCHEDULE with duration_kind == FAULT_DURATION_UNTIL_TRIGGER
//      (2): fault_type/target/the ARM trigger/repeat/params are captured
//      immediately into s_pending_until[slot_id] (indexed directly by
//      slot_id, 0..FAULT_ENGINE_MAX_SLOTS-1 -- the same range fault_engine's
//      own slot pool uses, so no separate id scheme is needed) but the slot
//      is NOT armed in fault_sched yet. duration_for_s is ignored for this
//      duration_kind.
//   2. SIMFW_CMD_FAULT_SET_UNTIL_TRIGGER {u16 slot_id, <trigger encoding,
//      byte-identical to FAULT_SCHEDULE's own ARM-trigger fields:
//      u8 trigger_kind, f64 trigger_a, f64 trigger_b, u16 trigger_ref,
//      u8 trigger_edge, char[24] event_name>} supplies the RELEASE trigger
//      and performs the actual fault_sched_schedule() call, combining it
//      with the fields step 1 parked. Only now does the slot become ARMED.
// A slot_id with no pending entry (step 1 was never sent for it, or it was
// already consumed by a prior SET_UNTIL_TRIGGER, or FAULT_CANCEL discarded
// it -- see handle_fault_cancel()) rejects SET_UNTIL_TRIGGER with
// ERR_BAD_ARGS. See docs/PROTOCOL.md section 5.6 for the wire spec in full
// and this pass's report for the exact PC-side (tools/PcTools) follow-up
// this implies -- payloads.py is out of scope for this pass.
typedef struct {
    bool pending;
    fault_sched_fault_type_t fault_type;
    uint16_t target;
    fault_trigger_t trigger;
    fault_repeat_t repeat;
    float params[4];
} pending_until_trigger_t;

static pending_until_trigger_t s_pending_until[FAULT_ENGINE_MAX_SLOTS];

// Decodes the wire's compact fault_trigger_t encoding (u8 trigger_kind, f64
// trigger_a, f64 trigger_b, u16 trigger_ref, u8 trigger_edge, char[24]
// event_name -- see handle_fault_schedule()'s doc comment / PROTOCOL.md
// section 5.6). Shared by FAULT_SCHEDULE's top-level ARM trigger and
// FAULT_SET_UNTIL_TRIGGER's RELEASE trigger, since fault_engine.h documents
// UNTIL_TRIGGER's nested trigger as "evaluated the same way as a top-level
// trigger" -- one wire shape, one decoder, for both. Returns false (and
// leaves *out zeroed) if trigger_kind is out of range; does not itself
// inspect r->overflow -- callers check that separately, same as every other
// handler in this file.
static bool decode_fault_trigger(arg_reader_t *r, fault_trigger_t *out)
{
    uint8_t trigger_kind = ar_u8(r);
    double trigger_a = ar_f64le(r);
    double trigger_b = ar_f64le(r);
    uint16_t trigger_ref = ar_u16le(r);
    uint8_t trigger_edge = ar_u8(r);
    char event_name[FAULT_ENGINE_MAX_NAME_LEN];
    ar_bytes(r, (uint8_t *)event_name, (uint8_t)sizeof(event_name));
    event_name[FAULT_ENGINE_MAX_NAME_LEN - 1] = '\0'; // defensive: force NUL termination regardless of wire content

    memset(out, 0, sizeof(*out));
    if (trigger_kind > (uint8_t)FAULT_TRIGGER_MANUAL) {
        return false;
    }

    out->kind = (fault_trigger_kind_t)trigger_kind;
    switch (out->kind) {
        case FAULT_TRIGGER_AT_SIM_TIME:
            out->at_sim_time_s = trigger_a;
            break;
        case FAULT_TRIGGER_AT_ZONE_TEMP:
            out->zone = (uint8_t)trigger_ref;
            out->temp_c = (float)trigger_a;
            out->temp_edge = (fault_temp_edge_t)trigger_edge;
            break;
        case FAULT_TRIGGER_ON_RELAY_EDGE:
            out->relay = (uint8_t)trigger_ref;
            out->relay_edge = (fault_relay_edge_t)trigger_edge;
            out->delay_s = trigger_a;
            break;
        case FAULT_TRIGGER_ON_EVENT:
            memcpy(out->event_name, event_name, sizeof(out->event_name));
            out->delay_s = trigger_a;
            break;
        case FAULT_TRIGGER_AFTER_FAULT:
            out->after_fault_slot = trigger_ref;
            out->delay_s = trigger_a;
            break;
        case FAULT_TRIGGER_RANDOM_IN:
            out->random_t0_s = trigger_a;
            out->random_t1_s = trigger_b;
            break;
        case FAULT_TRIGGER_MANUAL:
        default:
            break;
    }
    return true;
}

static void handle_fault_schedule(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                   uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);

    uint16_t slot_id = ar_u16le(&r);
    uint8_t fault_type = ar_u8(&r);
    uint16_t target = ar_u16le(&r);

    fault_trigger_t trigger;
    bool trigger_ok = decode_fault_trigger(&r, &trigger);

    uint8_t duration_kind = ar_u8(&r);
    double duration_for_s = ar_f64le(&r);

    uint8_t repeat_kind = ar_u8(&r);
    double repeat_period_s = ar_f64le(&r);
    double repeat_jitter_s = ar_f64le(&r);
    uint16_t repeat_n = ar_u16le(&r);

    float params[4];
    params[0] = ar_f32le(&r);
    params[1] = ar_f32le(&r);
    params[2] = ar_f32le(&r);
    params[3] = ar_f32le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    // fault_type's upper bound is FAULT_SCHED_TYPE_DUT_POWER_CUT, the
    // catalog's actual last value (fault_sched.h) -- NOT
    // FAULT_SCHED_TYPE_AMBIENT_SHIFT, which stopped being the last value
    // once THERMAL_MASS_SURPRISE/TC_LAG_STRESS/DUT_POWER_CUT were added by
    // the sim_engine/fault_sched gap-closure pass; the stale bound silently
    // rejected all three via FAULT_SCHEDULE (found and fixed this pass).
    if (r.overflow || !trigger_ok || fault_type > (uint8_t)FAULT_SCHED_TYPE_DUT_POWER_CUT ||
        duration_kind > (uint8_t)FAULT_DURATION_UNTIL_TRIGGER || repeat_kind > (uint8_t)FAULT_REPEAT_N_TIMES) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    fault_repeat_t repeat = {0};
    repeat.kind = (fault_repeat_kind_t)repeat_kind;
    repeat.period_s = repeat_period_s;
    repeat.jitter_s = repeat_jitter_s;
    repeat.n = repeat_n;

    if (duration_kind == (uint8_t)FAULT_DURATION_UNTIL_TRIGGER) {
        // Two-frame path (s_pending_until's doc comment above): park
        // everything but the release trigger, do not arm yet.
        if (slot_id >= FAULT_ENGINE_MAX_SLOTS) {
            rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
            *out_len = w.len;
            return;
        }
        s_pending_until[slot_id].pending = true;
        s_pending_until[slot_id].fault_type = (fault_sched_fault_type_t)fault_type;
        s_pending_until[slot_id].target = target;
        s_pending_until[slot_id].trigger = trigger;
        s_pending_until[slot_id].repeat = repeat;
        memcpy(s_pending_until[slot_id].params, params, sizeof(params));
        rw_u8(&w, SIMFW_CMD_STATUS_OK);
        rw_u16le(&w, slot_id);
        *out_len = w.len;
        return;
    }

    // A direct (PERMANENT/FOR) schedule on this slot_id supersedes any
    // still-pending UNTIL_TRIGGER parked on it (frame 1 sent, frame 2 never
    // arrived) -- discard the stale entry so a later, unrelated
    // SET_UNTIL_TRIGGER cannot resurrect it against this new schedule.
    if (slot_id < FAULT_ENGINE_MAX_SLOTS) {
        s_pending_until[slot_id].pending = false;
    }

    fault_duration_t duration = {0};
    duration.kind = (fault_duration_kind_t)duration_kind;
    duration.for_s = duration_for_s;

    uint16_t sid = fault_sched_schedule(slot_id, (fault_sched_fault_type_t)fault_type, target, &trigger, &duration,
                                          &repeat, params);
    if (sid == FAULT_ENGINE_INVALID_SLOT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u16le(&w, sid);
    *out_len = w.len;
}

// request: {u16 slot_id, <trigger encoding, same shape as FAULT_SCHEDULE's
// own ARM trigger -- see decode_fault_trigger()>}. Supplies FAULT_SCHEDULE's
// UNTIL_TRIGGER release trigger and performs the actual fault_sched_schedule()
// call, combining it with the fields FAULT_SCHEDULE parked in
// s_pending_until[slot_id] (see that struct's doc comment above
// handle_fault_schedule for the full two-frame design). Reply: {status,
// u16 slot_id echo}. ERR_BAD_ARGS if slot_id has no pending UNTIL_TRIGGER
// schedule (step 1 was never sent for it, or it was already consumed/
// cancelled).
static void handle_fault_set_until_trigger(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                            uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint16_t slot_id = ar_u16le(&r);

    fault_trigger_t release_trigger;
    bool trigger_ok = decode_fault_trigger(&r, &release_trigger);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || !trigger_ok || slot_id >= FAULT_ENGINE_MAX_SLOTS || !s_pending_until[slot_id].pending) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }

    pending_until_trigger_t *pend = &s_pending_until[slot_id];

    fault_duration_t duration = {0};
    duration.kind = FAULT_DURATION_UNTIL_TRIGGER;
    duration.until_trigger = release_trigger;

    uint16_t sid = fault_sched_schedule(slot_id, pend->fault_type, pend->target, &pend->trigger, &duration,
                                          &pend->repeat, pend->params);
    pend->pending = false; // consumed regardless of outcome -- resend FAULT_SCHEDULE to retry
    if (sid == FAULT_ENGINE_INVALID_SLOT) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    rw_u16le(&w, sid);
    *out_len = w.len;
}

static void handle_fault_cancel(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                 uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint16_t slot_id = ar_u16le(&r);

    // Discard any still-pending UNTIL_TRIGGER schedule on this slot (step 1
    // sent, step 2/FAULT_SET_UNTIL_TRIGGER never arrived) -- there is
    // nothing armed in fault_sched yet to cancel at the engine level for
    // that case, but the parked PC-side intent should not survive an
    // explicit cancel either.
    if (slot_id < FAULT_ENGINE_MAX_SLOTS) {
        s_pending_until[slot_id].pending = false;
    }

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || !fault_sched_cancel(slot_id)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

static void handle_fault_fire_now(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                                   uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint16_t slot_id = ar_u16le(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || !fault_sched_fire_now(slot_id)) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    *out_len = w.len;
}

// Max slots summarized per FAULT_LIST reply -- bounded so status + count +
// N * 15-byte entries always fits: 2 + 8*15 = 122.
#define SIMFW_FAULT_LIST_MAX_PER_REPLY 8u

// Reused across calls (single-threaded dispatch, cmd_task.c's only caller of
// fault_sched_list()) rather than a ~230-byte-per-slot x 32 local array,
// which would blow CMD_TASK_STACK_WORDS (cmd_task.h) many times over.
static fault_slot_t s_fault_list_buf[FAULT_ENGINE_MAX_SLOTS];

// request: {u8 start_index, u8 max_count} -- pagination over the fixed
// 32-slot pool (fault_sched_list() itself always returns from index 0);
// max_count is clamped to SIMFW_FAULT_LIST_MAX_PER_REPLY. Reply:
// {status, u8 returned_count, returned_count * {u16 slot_id, u8 state,
// u16 fault_type, u16 target, u32 fire_count, f32 active_since_s}}.
static void handle_fault_list(const uint8_t *args, uint8_t args_len, uint8_t *out, uint8_t *out_len,
                               uint8_t out_cap)
{
    arg_reader_t r;
    ar_init(&r, args, args_len);
    uint8_t start_index = ar_u8(&r);
    uint8_t max_count = ar_u8(&r);

    reply_writer_t w;
    rw_init(&w, out, out_cap);
    if (r.overflow || start_index >= FAULT_ENGINE_MAX_SLOTS) {
        rw_u8(&w, SIMFW_CMD_STATUS_ERR_BAD_ARGS);
        *out_len = w.len;
        return;
    }
    if (max_count > SIMFW_FAULT_LIST_MAX_PER_REPLY) {
        max_count = SIMFW_FAULT_LIST_MAX_PER_REPLY;
    }

    size_t total = fault_sched_list(s_fault_list_buf, FAULT_ENGINE_MAX_SLOTS);
    uint8_t returned = 0;
    rw_u8(&w, SIMFW_CMD_STATUS_OK);
    uint8_t *count_slot = &out[w.len]; // patched below once `returned` is known
    rw_u8(&w, 0);
    for (uint8_t i = start_index; i < total && returned < max_count && i < FAULT_ENGINE_MAX_SLOTS; i++) {
        const fault_slot_t *s = &s_fault_list_buf[i];
        rw_u16le(&w, s->slot_id);
        rw_u8(&w, (uint8_t)s->state);
        rw_u16le(&w, s->fault_type);
        rw_u16le(&w, s->target);
        rw_u32le(&w, s->fire_count);
        rw_f32le(&w, (float)s->active_since_s);
        if (w.overflow) {
            break;
        }
        returned++;
    }
    *count_slot = returned;
    *out_len = w.len;
}

static const cmd_table_entry_t s_fault_commands[] = {
    {SIMFW_CMD_FAULT_SCHEDULE, handle_fault_schedule},
    {SIMFW_CMD_FAULT_CANCEL, handle_fault_cancel},
    {SIMFW_CMD_FAULT_LIST, handle_fault_list},
    {SIMFW_CMD_FAULT_FIRE_NOW, handle_fault_fire_now},
    {SIMFW_CMD_FAULT_SET_UNTIL_TRIGGER, handle_fault_set_until_trigger},
};

// --- Dispatch table --------------------------------------------------------

// One row per command group (docs/DESIGN_NOTES.md section 5's table). `commands`/
// `command_count` are NULL/0 for every group but SYS today -- see this
// file's header comment for why that is deliberate and how a later agent
// extends it. Order matches DESIGN_NOTES.md section 5's table top-to-bottom, purely
// for readability; cmd_task_dispatch() below looks up by task_id, not index.
typedef struct {
    uint8_t task_id;
    const cmd_table_entry_t *commands;
    size_t command_count;
} cmd_group_t;

static const cmd_group_t s_groups[] = {
    {SIMFW_TASK_ID_SYS, s_sys_commands, sizeof(s_sys_commands) / sizeof(s_sys_commands[0])},
    {SIMFW_TASK_ID_MODEL, s_model_commands, sizeof(s_model_commands) / sizeof(s_model_commands[0])},
    {SIMFW_TASK_ID_TC, s_tc_commands, sizeof(s_tc_commands) / sizeof(s_tc_commands[0])},
    {SIMFW_TASK_ID_CT, s_ct_commands, sizeof(s_ct_commands) / sizeof(s_ct_commands[0])},
    {SIMFW_TASK_ID_RELAY, s_relay_commands, sizeof(s_relay_commands) / sizeof(s_relay_commands[0])},
    {SIMFW_TASK_ID_IO, s_io_commands, sizeof(s_io_commands) / sizeof(s_io_commands[0])},
    {SIMFW_TASK_ID_FAULT, s_fault_commands, sizeof(s_fault_commands) / sizeof(s_fault_commands[0])},
    {SIMFW_TASK_ID_EVT, NULL, 0},
};
#define CMD_TASK_GROUP_COUNT (sizeof(s_groups) / sizeof(s_groups[0]))

// req->length >= 1 is usb_owner's own delivery precondition
// (usb_owner_handle_deliver() drops length == 0 before ever posting to this
// task's inbox), so payload[0] (the subcommand byte) is always present here.
static void cmd_task_dispatch(const cmd_task_request_t *req, uint8_t *out, uint8_t *out_len)
{
    uint8_t cmd_id = req->payload[0];
    const uint8_t *args = req->payload + 1;
    uint8_t args_len = (uint8_t)(req->length - 1u);

    for (size_t g = 0; g < CMD_TASK_GROUP_COUNT; g++) {
        if (s_groups[g].task_id != req->dst_task) {
            continue;
        }
        for (size_t c = 0; c < s_groups[g].command_count; c++) {
            if (s_groups[g].commands[c].cmd_id == cmd_id) {
                s_groups[g].commands[c].handler(args, args_len, out, out_len, BENCHPROTO_FRAME_MAX_PAYLOAD);
                return;
            }
        }
        // Group exists but this cmd_id has no handler yet -- reserved
        // (e.g. SYS's RESET_SIM/SET_TIMESCALE/SET_SEED) or the whole group
        // is still a stub (MODEL/TC/CT/RELAY/IO/FAULT/EVT). Clean, defined
        // "not yet implemented" answer, not a silent drop.
        out[0] = SIMFW_CMD_STATUS_ERR_NOT_IMPL;
        *out_len = 1;
        return;
    }

    // dst_task matched none of s_groups[] -- shouldn't happen: usb_owner
    // only delivers frames addressed to a task_id it registered
    // (usb_owner_register_task(), called below in cmd_task_start() for
    // every id in s_groups[]), so this is an internal inconsistency, not
    // untrusted wire input. Reported rather than silently dropped so it is
    // visible if it ever does happen (e.g. a future s_groups[] edit that
    // forgets to also register the new id).
    out[0] = SIMFW_CMD_STATUS_ERR_INTERNAL;
    *out_len = 1;
}

static void cmd_task_fn(void *arg)
{
    (void)arg;

    for (;;) {
        cmd_task_request_t req;
        if (xQueueReceive(s_inbox, &req, portMAX_DELAY) != pdTRUE) {
            continue;
        }

        uint8_t reply[BENCHPROTO_FRAME_MAX_PAYLOAD];
        uint8_t reply_len = 0;
        cmd_task_dispatch(&req, reply, &reply_len);

        (void)usb_owner_send_reply(req.dst_task, req.src_device, req.src_task, req.msg_index, reply, reply_len);
    }
}

bool cmd_task_start(void)
{
    s_inbox = xQueueCreate(CMD_TASK_INBOX_DEPTH, sizeof(cmd_task_request_t));
    if (!s_inbox) {
        return false;
    }

    // Register every command group as an addressable task on usb_owner's
    // link (BENCHPROTO.md sec 6) before this function returns -- safe
    // because usb_owner_start() (main.c's existing call, before this one)
    // already initialized the underlying benchproto_link_t synchronously;
    // see usb_owner_start()'s own doc comment.
    for (size_t g = 0; g < CMD_TASK_GROUP_COUNT; g++) {
        if (!usb_owner_register_task(s_groups[g].task_id)) {
            return false;
        }
    }

    BaseType_t ok = xTaskCreate(cmd_task_fn, "cmd_task", CMD_TASK_STACK_WORDS, NULL, SIMFW_PRIO_CMD_TASK,
                                 &s_task_handle);
    if (ok != pdPASS) {
        return false;
    }

    vTaskCoreAffinitySet(s_task_handle, SIMFW_CORE_ELASTIC_PATH);
    return true;
}

QueueHandle_t cmd_task_get_inbox(void)
{
    return s_inbox;
}
