// totp.h -- RFC 6238 (TOTP) / RFC 4226 (HOTP) core, plus the RFC 4648
// base32 encode/decode this board's otpauth:// enrollment URI needs.
// docs/TOTP_PASSWORD_RESET_PLAN.md sections 1/3, work tranche WT-A.
//
// PURE, NO I/O, NO ESP-IDF DEPENDENCY -- host-testable against RFC 6238
// Appendix B's published vectors, same discipline as ota_auth.c/
// login_ip_scope.c. This file does not read or write NVS, does not
// generate randomness, and does not know about HTTP -- see totp_config.h
// (persist/) for the NVS-backed secret/replay-counter store and
// totp_enroll_http.c/auth_forgot_reset_http.c (http/) for the HTTP glue.
//
// WHY A HAND-ROLLED SHA-1/HMAC INSTEAD OF mbedtls/PSA: this codebase's own
// psa/crypto.h host-test stub (App/test/stubs/psa/crypto.h) is an explicit,
// documented FAKE -- "not a real HMAC/SHA-256 implementation" -- and the
// classic mbedtls_md_hmac*() API is compiled out of the vendored mbedtls
// 4.x/TF-PSA-Crypto build (see ota_http.c's hmac_sha256() comment). Neither
// gives WT-D a path to validate against RFC 6238 Appendix B's exact test
// vectors on the host, which this plan's acceptance criteria requires
// ("RFC 6238 Appendix B vectors pass exactly"). A small, self-contained,
// RFC 3174 (SHA-1) + RFC 2104 (HMAC) implementation compiled identically on
// both the host test binary and the ESP32-S3 target closes that gap and
// keeps totp.c dependency-free, matching the pure/glue split every other
// auth-adjacent module in this tree already uses.
//
// SHA-1 is used here ONLY as RFC 6238's mandated MAC primitive for
// interoperability with commodity authenticator apps (see the compatibility
// table in docs/TOTP_PASSWORD_RESET_PLAN.md section 1) -- it is not used,
// and must never be used, as a general-purpose hash anywhere else in this
// tree.
#ifndef KILNCTL_TOTP_H
#define KILNCTL_TOTP_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// --- Fixed RFC 6238 parameters (plan section 1: NOT configurable) ---------

#define TOTP_SECRET_LEN   20u   // 160 bits, esp_random()-generated by the caller
#define TOTP_DIGITS       6u
#define TOTP_PERIOD_S     30u
#define TOTP_WINDOW_STEPS 1u    // accept counter-1, counter, counter+1

// --- SHA-1 / HMAC-SHA1 (RFC 3174 / RFC 2104) ------------------------------

#define TOTP_SHA1_DIGEST_LEN 20u

// One-shot SHA-1 over `data[0..len)`. Never called on secret-derived data
// alone in a place a timing attack could matter -- only as HMAC-SHA1's
// internal primitive below.
void totp_sha1(const uint8_t *data, size_t len, uint8_t out[TOTP_SHA1_DIGEST_LEN]);

// RFC 2104 HMAC-SHA1. `key`/`key_len` is the TOTP secret; `msg`/`msg_len`
// is the 8-byte big-endian counter for HOTP/TOTP use, but this function
// itself is general (block-size key handling per RFC 2104 section 2).
void totp_hmac_sha1(const uint8_t *key, size_t key_len, const uint8_t *msg, size_t msg_len,
                     uint8_t out[TOTP_SHA1_DIGEST_LEN]);

// --- HOTP dynamic truncation (RFC 4226 section 5.3) -----------------------

// `digits` is caller-supplied (not hardcoded to TOTP_DIGITS) specifically so
// WT-D's host tests can validate RFC 6238 Appendix B's own vectors, which
// are published as 8-digit codes, directly -- the HMAC/counter math is
// identical up to the final `% 10^digits`; only the modulus differs between
// the 8-digit RFC vectors and this board's 6-digit codes. Returns the code
// as an integer in [0, 10^digits).
uint32_t totp_hotp_truncate(const uint8_t *secret, size_t secret_len, uint64_t counter,
                             unsigned digits);

// Convenience wrapper: HOTP at this board's fixed TOTP_DIGITS.
static inline uint32_t totp_hotp_code(const uint8_t *secret, size_t secret_len, uint64_t counter)
{
    return totp_hotp_truncate(secret, secret_len, counter, TOTP_DIGITS);
}

// TOTP counter for `unix_time_s` at the fixed TOTP_PERIOD_S step.
static inline uint64_t totp_counter_for_time(uint64_t unix_time_s)
{
    return unix_time_s / TOTP_PERIOD_S;
}

// --- Constant-time compare -------------------------------------------------

// Same discipline as web_auth_constant_time_equal()/ota_auth_constant_time_
// equal(): a code-derived comparison must not short-circuit on the first
// mismatched byte. `len` itself is NOT secret (both buffers are always
// TOTP_DIGITS-length decimal strings in this module's own callers) so only
// the byte comparison loop needs to run full-length.
bool totp_constant_time_equal(const uint8_t *a, const uint8_t *b, size_t len);

// --- Verification with replay guard + clock-skew window -------------------

// `code` is a NUL-terminated decimal digit string, exactly TOTP_DIGITS
// digits (rejected otherwise -- never partially parsed). `last_accepted_
// counter` is the highest TOTP counter value already accepted for this
// secret (0 if none yet -- counter 0 is 1970-01-01T00:00:00Z, never a real
// TOTP window on a board with SNTP sync, so 0 is a safe "never accepted"
// sentinel). Tries counters {counter, counter-1, counter+1} (current step
// first) within the +/-1 step window; a candidate <= last_accepted_counter
// is skipped outright (replay refused) without being compared. On a match,
// writes the matched counter to *out_matched_counter (the caller must
// persist it, both in RAM and in NVS, as the new last_accepted_counter --
// see totp_config.h) and returns true. Returns false if `code` does not
// parse as exactly TOTP_DIGITS digits, or no candidate in the window
// matches, or the only matching candidate(s) were already-used (<=
// last_accepted_counter).
bool totp_verify(const uint8_t *secret, size_t secret_len, const char *code,
                  uint64_t unix_time_s, uint64_t last_accepted_counter,
                  uint64_t *out_matched_counter);

// --- Base32 (RFC 4648 section 6, no padding) -------------------------------

// Encodes `data[0..len)` into `out` (at least base32-length+1 bytes, for the
// NUL) using the standard unpadded RFC 4648 alphabet. Returns the encoded
// length (excluding NUL), or 0 if `out_cap` is too small.
size_t totp_base32_encode(const uint8_t *data, size_t len, char *out, size_t out_cap);

// Decodes an unpadded (or padded -- '=' is skipped) base32 string into
// `out`. Case-insensitive. Returns the decoded length, or 0 on a malformed
// input (an alphabet character outside A-Z2-7, ignoring case and '=') or
// insufficient `out_cap`.
size_t totp_base32_decode(const char *text, uint8_t *out, size_t out_cap);

// --- otpauth:// URI (plan section 1's fixed-parameter URI) -----------------

// Writes `otpauth://totp/kilnCtl:<username>?secret=<base32>&issuer=kilnCtl&
// algorithm=SHA1&digits=6&period=30` into `out`. `username` is assumed
// already validated/short (WEB_AUTH_USERNAME_MAX-class caller); this
// function truncates rather than overflows if it doesn't fit. Returns the
// written length (excluding NUL), or 0 if `out_cap` is too small even for
// the fixed parts.
size_t totp_build_otpauth_uri(const char *username, const uint8_t *secret, size_t secret_len,
                               char *out, size_t out_cap);

#ifdef __cplusplus
}
#endif

#endif // KILNCTL_TOTP_H
