// main.c -- SimFW entry point. Build/task skeleton only: creates and
// schedules the ten single-owner tasks from docs/DESIGN_NOTES.md section 4.1's task
// map, each currently an idling stub (src/tasks/*.c). No peripheral is
// actually driven yet -- PIO SPI emulation, CT waveform synthesis, I2C/
// expander logic and USB protocol handling are later work, filled into
// these same task bodies without touching this file or any sibling task
// file (single-owner-per-peripheral doctrine, DESIGN_NOTES.md section 4's opening
// paragraph).
//
// Mirrors ../SaftyFW/src/main.c's shape (stdio bring-up, start every task in
// priority order, start the scheduler) but without that project's boot
// sequence (no GPIO6 safety latch, no watchdog, no config-store/MAX31856
// bring-up here -- SimFW is a bench tool, not the thing being protected, and
// none of that machinery exists yet for this project regardless).
#include <stdio.h>

#include "pico/stdlib.h"

#include "FreeRTOS.h"
#include "task.h"

#include "build_info.h" // generated by ../gen_build_info.cmake, see CMakeLists.txt

#include "drivers/console_sink.h"
#include "drivers/ct_wave_i2s.h"
#include "drivers/simfw_fatal.h"

#include "tasks/cmd_task.h"
#include "tasks/fault_sched.h"
#include "tasks/i2c_owner.h"
#include "tasks/log_task.h"
#include "tasks/sim_engine.h"
#include "tasks/spi_emu_a.h"
#include "tasks/spi_emu_b.h"
#include "tasks/telemetry.h"
#include "tasks/usb_owner.h"
#include "tasks/wave_owner.h"

// ---------------------------------------------------------------------------
// DMA channel budget -- docs/HARDWARE.md section 1b.
//
// The RP2040's 12 DMA channels are one global pool with no per-peripheral
// partitioning. Every dma_claim_unused_channel() call site in the fixture
// now routes a failure through drivers/simfw_fatal.h, which halts loudly
// (matching the neighbouring pio_claim_unused_sm(pio, true) panics) instead
// of the silent degrade this budget used to be the only defense against
// (section 1b.5: a fixture that boots, enumerates and answers commands while
// having no CT output or one dead SPI bus -- fixed this pass). That does NOT
// make this compile-time check redundant: catching a 13th channel at build
// time, before anyone is standing at the bench, is still strictly better
// than catching it via a bench-time halt on whichever core claims last.
//
// This file is the only translation unit that sees every DMA claimant's
// count constant at once -- the drivers cannot check it themselves (a driver
// including a task header would invert the layering) and no single owner can
// see the others' numbers, which is precisely the class of mistake section 1b
// exists to prevent. tools/check_single_owner.ps1 re-derives the same sum from
// the same three headers, so the arithmetic is also enforced without a build,
// and that script fails if this assertion is ever deleted.
//
// The formula is section 1b.2's closed form:
//
//     channels = CT zones + sum over buses of (chips_on_bus + 2)
//
// where the +2 per bus is that bus's `dma_load` + `dma_data` (section 1b.1),
// and each bus's chip count is one `dma_sniff[i]` per emulated chip.
// CT_WAVE_I2S_NUM_MODULES (2, one DMA channel per UDA1334A module) replaces
// the retired ct_wave_pwm.c's CT_WAVE_PWM_NUM_CHANNELS (3) here, per
// docs/DESIGN_NOTES.md section 3.3's 2026-08-23 PWM->I2S decision -- the DMA
// count went down even though ct_wave_i2s.c cannot actually run yet
// (docs/HARDWARE.md section 1b.7's PIO1 program-memory blocker is a separate
// budget, not this one). If a third DMA claimant is ever added, add its term
// here AND to section 1b's table AND to check_single_owner.ps1's
// $dmaBudgetTerms -- all three, in the same commit.
#define SIMFW_DMA_CHANNELS_CLAIMED                                            \
    (CT_WAVE_I2S_NUM_MODULES + (SPI_EMU_A_CHANNEL_COUNT + 2u) +              \
     (SPI_EMU_B_CHANNEL_COUNT + 2u))

_Static_assert(SIMFW_DMA_CHANNELS_CLAIMED <= NUM_DMA_CHANNELS,
               "SimFW DMA budget exceeded: the CT wave synth and the two PIO "
               "SPI buses together claim more than the RP2040's "
               "NUM_DMA_CHANNELS channels. Every claim now halts loudly via "
               "simfw_fatal() on exhaustion (drivers/simfw_fatal.h) rather "
               "than degrading silently, but that is a bench-time halt -- "
               "catching the overrun here, at compile time, is still better. "
               "Free a channel (see docs/HARDWARE.md section 1b.4, the only "
               "slack that exists) or reduce a channel-count constant.");

// FreeRTOSConfig.h turns on configCHECK_FOR_STACK_OVERFLOW (2) and
// configUSE_MALLOC_FAILED_HOOK (1) unconditionally, matching SaftyFW's
// choice -- cheap insurance, and the kernel requires these two hooks to
// exist at link time regardless. Halting in place rather than resetting, so
// a debugger attached over SWD (this bench fixture's flashing/debug path,
// DESIGN_NOTES.md section 3.1) can see exactly where it happened instead of the
// failure hiding behind a watchdog-looking reboot.
//
// BOTH HOOKS NOW ROUTE THROUGH simfw_fatal() -- they used to just
// taskDISABLE_INTERRUPTS() and spin, which is INDISTINGUISHABLE AT THE BENCH
// from a healthy-but-quiet fixture: no LED, no USB, nothing. That silence is
// exactly what let telemetry_task's real stack overflow (see this task's
// bench report: telemetry_build_and_send_state_frame() alone measured 10736
// bytes of stack against a 1024-byte task stack, an order of magnitude over)
// go undiagnosable from a dark board with no debug probe attached. A hook
// that never lights the LED turns "the kernel caught a real bug" into "the
// bench operator has no idea whether the fixture is dead or just idle."
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    // printf() here is belt-and-braces: simfw_fatal() itself prints this
    // same information first thing (simfw_fatal.c), but this call site is
    // cheap insurance against that changing later, and it means the hook
    // path is traceable even by someone reading only main.c.
    printf("[freertos] vApplicationStackOverflowHook: stack overflow in task \"%s\"\r\n",
           pcTaskName ? pcTaskName : "?");
    fflush(stdout);
    simfw_fatal("freertos", "stack overflow in task \"%s\"", pcTaskName ? pcTaskName : "?");
}

void vApplicationMallocFailedHook(void)
{
    printf("[freertos] vApplicationMallocFailedHook: heap allocation failed (configTOTAL_HEAP_SIZE exhausted)\r\n");
    fflush(stdout);
    simfw_fatal("freertos", "heap allocation failed (configTOTAL_HEAP_SIZE exhausted)");
}

// --- Boot-stage beacon -------------------------------------------------------
// GPIO25 (onboard LED) -- see simfw_fatal.c's header for why this pin has no
// owner until now and why a heartbeat/beacon must yield it the instant
// simfw_fatal() is entered rather than fight for it. This beacon and
// simfw_fatal() never actually contend for the pin in practice: this
// function only ever runs pre-scheduler, in main()'s own straight-line call
// sequence on core 0, and simfw_fatal() halts whichever core called it
// (disabling interrupts, looping forever) rather than returning -- so a
// fatal firing mid-stage simply never returns control to finish that
// stage's blink group, and no two writers are ever mid-sequence on GPIO25 at
// once. This is the "distinct, countable blink pattern per stage" the bench
// operator needs with no debug probe attached (see
// docs/BENCH_RUNBOOK.md's decode table) -- added after a real bench boot
// failure (dark LED, no USB) turned out to be a task stack overflow with
// zero visible signal, see vApplicationStackOverflowHook() above.
//
// 2026-08-23 fine-grained pass: the original scheme (N short flashes for
// stage N, N in 1..10) was replaced with a base-5 long/short encoding after
// a SECOND dark-board bench failure that never even reached stage 1 -- the
// stage count now runs 1..14 (four new checkpoints ahead of the first
// _start() call, see main()'s own comments), and counting fourteen
// back-to-back 150 ms flashes by eye is unreliable. The new encoding reads
// like a two-digit odometer instead of a tally: stage N is
// floor(N/5) LONG flashes (one per group of five), then -- ONLY if there is
// a nonzero remainder -- a medium gap and (N mod 5) SHORT flashes. N is
// recovered as 5*longs + shorts. Examples: stage 5 is exactly one long
// flash and nothing else (5 = 5*1 + 0); stage 14 is two long flashes, a
// gap, then four short flashes (14 = 5*2 + 4); stage 1 is zero long
// flashes (no leading gap either -- see the `longs > 0` guard below) and
// one short flash. A long dark SIMFW_BOOT_BEACON_GROUP_GAP_MS gap still
// separates one stage's whole encoded number from the next, exactly as
// before.
//
// Deliberately NOT using pico-sdk's sleep_ms()/busy_wait_ms() distinction
// here beyond picking busy_wait_ms(): no FreeRTOS tick is running yet
// pre-scheduler, so sleep_ms() (which can rely on the SDK's own low-power
// wait) is fine too, but busy_wait_ms() is the same primitive
// simfw_fatal.c's own blink burst already uses -- one busy-wait convention
// for every pre-scheduler LED sequence in this file, not two.
#define SIMFW_BOOT_BEACON_LED_GPIO        25u // same physical LED as simfw_fatal.c's SIMFW_FATAL_LED_GPIO
#define SIMFW_BOOT_BEACON_LONG_ON_MS      400u
#define SIMFW_BOOT_BEACON_LONG_OFF_MS     250u
#define SIMFW_BOOT_BEACON_SHORT_ON_MS     120u
#define SIMFW_BOOT_BEACON_SHORT_OFF_MS    180u
#define SIMFW_BOOT_BEACON_SUBGROUP_GAP_MS 500u  // between the long sub-group and the short sub-group, only emitted when both are non-empty
#define SIMFW_BOOT_BEACON_GROUP_GAP_MS    1200u // long dark gap between stage numbers -- lets a human count flashes reliably
#define SIMFW_BOOT_BEACON_STAGE_COUNT     14u   // highest stage number main() ever emits -- see the two comment blocks above main()'s SIMFW_BOOT_STAGE calls for what each number means; docs/BENCH_RUNBOOK.md section 1.3 has the same table
#define SIMFW_BOOT_BEACON_REPLAY_COUNT    3u    // extra full 1..14 replays once boot genuinely finishes, purely so a human can recount without needing a fresh power cycle -- see main()'s comment just above vTaskStartScheduler()

static void simfw_boot_beacon(uint32_t stage_number)
{
    uint32_t longs = stage_number / 5u;
    uint32_t shorts = stage_number % 5u;

    for (uint32_t i = 0; i < longs; i++) {
        gpio_put(SIMFW_BOOT_BEACON_LED_GPIO, 1);
        busy_wait_ms(SIMFW_BOOT_BEACON_LONG_ON_MS);
        gpio_put(SIMFW_BOOT_BEACON_LED_GPIO, 0);
        busy_wait_ms(SIMFW_BOOT_BEACON_LONG_OFF_MS);
    }
    if (longs > 0 && shorts > 0) {
        busy_wait_ms(SIMFW_BOOT_BEACON_SUBGROUP_GAP_MS);
    }
    for (uint32_t i = 0; i < shorts; i++) {
        gpio_put(SIMFW_BOOT_BEACON_LED_GPIO, 1);
        busy_wait_ms(SIMFW_BOOT_BEACON_SHORT_ON_MS);
        gpio_put(SIMFW_BOOT_BEACON_LED_GPIO, 0);
        busy_wait_ms(SIMFW_BOOT_BEACON_SHORT_OFF_MS);
    }
    busy_wait_ms(SIMFW_BOOT_BEACON_GROUP_GAP_MS);
}

// --- Post-scheduler heartbeat -------------------------------------------------
// configUSE_IDLE_HOOK is on (FreeRTOSConfig.h) solely for this: a slow,
// unmistakable "the scheduler is alive and core 0 is idling normally"
// signal, so a healthy fixture's final LED state is never just "dark" (which
// this task's bench report shows is otherwise indistinguishable from a
// silently hung fixture -- see vApplicationStackOverflowHook()'s comment).
// One brief 100 ms flash every ~2 s: short and infrequent enough that it
// cannot be mistaken for a boot-stage group (150/150 ms flashes clustered
// back-to-back, this task's own SIMFW_BOOT_BEACON_* timing) or for
// simfw_fatal()'s 10x 100/100 ms burst-then-solid-on. Runs only on core 0's
// idle task (configUSE_PASSIVE_IDLE_HOOK is 0, configIDLE_AFFINITY is 0) --
// core 1 never calls this. Non-blocking (time_us_64()-gated, not a sleep) so
// it never delays the idle task's own tickless-idle/yield bookkeeping.
// Naturally stops the instant simfw_fatal() disables interrupts and loops
// forever: the idle task simply never runs again to call this, so there is
// no explicit hand-off needed, matching simfw_fatal.c's "yield the pin"
// requirement by construction rather than by an added flag.
#define SIMFW_HEARTBEAT_PERIOD_MS 2000u
#define SIMFW_HEARTBEAT_ON_MS     100u

void vApplicationIdleHook(void)
{
    uint32_t phase = (uint32_t)(time_us_64() / 1000u) % SIMFW_HEARTBEAT_PERIOD_MS;
    gpio_put(SIMFW_BOOT_BEACON_LED_GPIO, phase < SIMFW_HEARTBEAT_ON_MS ? 1 : 0);
}

int main(void)
{
    // Group 1 -- MUST be the literal first two statements this function
    // executes, ahead of stdio_init_all() and everything else. 2026-08-23,
    // second dark-board bench pass: the previous instrumentation (this same
    // file, one pass earlier) put its first beacon after spi_emu_a_start(),
    // and a real bench failure showed a fixture that was completely dark
    // from power-on -- not even that first group. That leaves two
    // possibilities this file cannot tell apart on its own: something
    // hung/crashed inside main() before reaching spi_emu_a_start() (in
    // stdio_init_all(), console_sink_register(), or
    // simfw_fatal_install_cross_core_halt()), or the board never reached
    // main() at all (pico-sdk/crt0 runtime_init, boot ROM, or the flash
    // image itself). Lighting the LED as the very first thing main() does,
    // before any of those calls, splits that ambiguity in two: if group 1
    // itself never appears, the fault is before main() and no amount of
    // further instrumentation inside this function can see it -- reach for
    // a debug probe instead of respinning this file again. See
    // docs/BENCH_RUNBOOK.md section 1.3 for the full decode table.
    gpio_init(SIMFW_BOOT_BEACON_LED_GPIO);
    gpio_set_dir(SIMFW_BOOT_BEACON_LED_GPIO, GPIO_OUT);
    simfw_boot_beacon(1);

    // stdio_init_all() now brings up UART0 (pico_stdio_uart is enabled,
    // CMakeLists.txt, 2026-08-23 bench boot-debug pass) on GPIO16/17 at
    // 115200 8N1 -- see CMakeLists.txt's PICO_DEFAULT_UART* compile
    // definitions and docs/HARDWARE.md section 1's footnote. Bring-up order
    // otherwise matches SaftyFW's own main(), so every printf() below it --
    // and everything simfw_fatal() prints -- has a live UART to write to.
    stdio_init_all();
    // Group 2 -- stdio_init_all() returned. If group 1 appeared but group 2
    // never does, stdio_init_all() itself is where this board hangs (the
    // proven-good tools/boot_probe/blink_uart control image calls this same
    // function, same UART pins/baud, and blinks fine standalone -- so this
    // would mean something SimFW links in changes stdio_init_all()'s own
    // behavior, not that the call is broken in general).
    simfw_boot_beacon(2);

    // Registers the CDC1 console sink as a SECOND stdio driver alongside the
    // UART one stdio_init_all() just brought up (drivers/console_sink.c) --
    // 2026-08-23, "give SimFW a second USB CDC interface, dedicated to
    // console/log output". Every printf()/puts() call from here on
    // (including the very next line) is mirrored to BOTH channels: the UART
    // stays the only channel that has ever actually shown output on this
    // dark-board bench investigation, so it must keep working exactly as
    // before (this call only ADDS a second driver, it does not touch
    // stdio_uart's own registration); CDC1 is initially a no-op destination
    // regardless -- usb_owner's TinyUSB init hasn't run yet at this point in
    // boot (usb_owner_start() is still several SIMFW_BOOT_STAGE calls away,
    // below), and usb_owner_console_write() drops silently until it has (see
    // that function's own doc comment) -- so registering this early is safe
    // by construction, not just convenient.
    console_sink_register();

    // FIRST LINE OF TRACE OUTPUT, unmissable and unconditional: if this
    // never appears on the UART, either GPIO16/17 are wired wrong on this
    // bench, or something hung inside stdio_init_all() itself (see
    // main.c's investigation note further down for why that is considered
    // unlikely but not impossible), or the board never got this far at all
    // (pre-main() SDK runtime init, or the flash image itself). Every
    // subsequent trace point in this function assumes THIS line printed.
    printf("\r\n\r\n=== SimFW booting === commit %s%s, built %s %s ===\r\n",
           SIMFW_FW_GIT_COMMIT, SIMFW_FW_GIT_DIRTY ? "-dirty" : "",
           SIMFW_FW_BUILD_DATE, SIMFW_FW_BUILD_TIME);
    fflush(stdout);

    // MUST run before vTaskStartScheduler() and before any core-1 task can
    // possibly fire simfw_fatal() -- see simfw_fatal.h's "CROSS-CORE HALT"
    // comment. Registers the SIO_IRQ_PROC0 handler that lets a core-1 fatal
    // (spi_emu_a/b's DMA/PIO claims, SIMFW_CORE_RT_PATH) also halt core 0,
    // so the fixture cannot keep answering USB/telemetry as if healthy while
    // one bus is silently dead. Core 0 is the only core running at this
    // point in boot (the FreeRTOS RP2040 SMP port launches core 1 lazily,
    // inside vTaskStartScheduler() below), so irq_set_exclusive_handler()/
    // irq_set_enabled() are guaranteed to bind to core 0's own NVIC here.
    simfw_fatal_install_cross_core_halt();
    printf("[boot] cross-core halt handler installed (SIO_IRQ_PROC0)\r\n");
    fflush(stdout);
    // Group 3 -- cross-core halt handler installed. NOTE: this is also the
    // point past which a KNOWN, SEPARATE, ALREADY-CONFIRMED bug lies in wait
    // several stages later: the FreeRTOS RP2040 SMP port's own
    // xPortStartSchedulerOnCore() (FreeRTOS-Kernel's
    // portable/ThirdParty/GCC/RP2040/port.c) installs a SECOND exclusive
    // handler on this same SIO_IRQ_PROC0 via irq_set_exclusive_handler() when
    // vTaskStartScheduler() runs, and pico-sdk's irq_set_exclusive_handler()
    // hard_assert()s (hardware_irq/irq.c) if the vtable slot already holds a
    // different handler than the one being installed -- which it will,
    // because the line above just put a different one there. That failure
    // is not this investigation's target (it can only fire AFTER group 14,
    // once every _start() call below has already returned), so it is
    // reported, not fixed, here -- see this pass's investigation notes.
    simfw_boot_beacon(3);

    // Boot-stage beacon init -- see simfw_boot_beacon()'s comment above.
    // gpio_init()/gpio_set_dir() here, ONCE MORE, is deliberately the same
    // pattern simfw_fatal()'s own first two lines use for this pin; harmless
    // to "re-init" (both this and group 1's earlier init are core-0-only,
    // pre-scheduler, sequential, never concurrent) -- kept as its own
    // checkpoint rather than folded into group 1 so a hang specifically
    // between the cross-core-halt install and this re-init is still visible.
    gpio_init(SIMFW_BOOT_BEACON_LED_GPIO);
    gpio_set_dir(SIMFW_BOOT_BEACON_LED_GPIO, GPIO_OUT);
    printf("[boot] beacon GPIO%u ready\r\n", SIMFW_BOOT_BEACON_LED_GPIO);
    fflush(stdout);
    // Group 4 -- the last pre-task-start checkpoint. Every _start() call
    // below gets its own group (5 through 14, see SIMFW_BOOT_STAGE's calls),
    // so reaching group 4 but nothing beyond it means the very first
    // _start() call (spi_emu_a_start()) is where this board hangs.
    simfw_boot_beacon(4);

    // Start every task, in priority order (highest first), matching
    // docs/DESIGN_NOTES.md section 4.1's table and SaftyFW's own main.c convention.
    // Each _start() function pins its own task's core affinity
    // (task_priorities.h's SIMFW_CORE_RT_PATH / SIMFW_CORE_ELASTIC_PATH) --
    // this file does not set affinity itself, so there is exactly one place
    // per task that can get it wrong, not two.
    //
    // No return value is checked here, but that is no longer "every task
    // body is just an idle loop with nothing that can fail beyond
    // xTaskCreate()" -- it stopped being true the moment wave_owner_start()
    // (ct_wave_i2s_init()) and spi_emu_a/b_start() (max31856_pio_engine_init())
    // started claiming DMA/PIO resources from shared, exhaustible pools
    // (docs/HARDWARE.md section 1b). What makes the (void) discards
    // below still defensible is that a claim failure no longer returns
    // false up this chain at all: every dma_claim_unused_channel() call site
    // now halts loudly through drivers/simfw_fatal.h on exhaustion (see that
    // header, and ct_wave_i2s.c/max31856_pio_engine.c's call sites) instead
    // of degrading silently the way it used to -- ct_wave_i2s_init() is in
    // fact EXPECTED to reach simfw_fatal() on the current build, since PIO1
    // does not have the 8 free program-memory words it needs (section
    // 1b.7); the fixture halts loudly at boot rather than running with a
    // silently-dead CT path. What a _start() function can
    // still fail on -- and what these (void)s still discard -- is a plain
    // FreeRTOS allocation failure (xTaskCreate()/xQueueCreate()/
    // xSemaphoreCreateMutex() under heap pressure), which remains
    // "logged-and-continued, nothing fatal" the way SaftyFW's own main()
    // documents, minus the logging until log_task is real (there is no log
    // sink running yet to report a failure to -- log_task itself is one of
    // the tasks being started). TODO: once log_task/telemetry have real
    // bodies, capture and report these.
    // SIMFW_BOOT_STAGE: prints "entering X_start()" immediately before the
    // call and "X_start() ok" immediately after, so a hang inside any one
    // _start() is bracketed by an "entering" line with no matching "ok" --
    // the UART trace equivalent of simfw_boot_beacon()'s "which blink group
    // was the last one seen" bench signal, and unlike the beacon it needs no
    // human to count flashes. do/while(0) so each call site below still
    // reads as one statement (semicolon required, same as any other
    // function-like macro in this codebase).
#define SIMFW_BOOT_STAGE(label, start_call, stage_number)                    \
    do {                                                                     \
        printf("[boot] entering " label "_start()\r\n");                    \
        fflush(stdout);                                                     \
        (void)(start_call);                                                 \
        printf("[boot] " label "_start() ok\r\n");                          \
        fflush(stdout);                                                     \
        simfw_boot_beacon(stage_number);                                    \
    } while (0)

    // Stage numbers renumbered 5..14 (2026-08-23 fine-grained pass) to sit
    // after the four new pre-task-start checkpoints above (groups 1-4)
    // without colliding with them -- every group number main() ever emits
    // is now distinct, 1 through SIMFW_BOOT_BEACON_STAGE_COUNT (14).
    SIMFW_BOOT_STAGE("spi_emu_a", spi_emu_a_start(), 5);
    SIMFW_BOOT_STAGE("spi_emu_b", spi_emu_b_start(), 6);
    SIMFW_BOOT_STAGE("wave_owner", wave_owner_start(), 7);
    SIMFW_BOOT_STAGE("sim_engine", sim_engine_start(), 8);
    SIMFW_BOOT_STAGE("usb_owner", usb_owner_start(), 9);
    SIMFW_BOOT_STAGE("cmd_task", cmd_task_start(), 10);
    SIMFW_BOOT_STAGE("fault_sched", fault_sched_start(), 11);
    SIMFW_BOOT_STAGE("i2c_owner", i2c_owner_start(), 12);
    SIMFW_BOOT_STAGE("telemetry", telemetry_start(), 13);
    SIMFW_BOOT_STAGE("log_task", log_task_start(), 14);

#undef SIMFW_BOOT_STAGE

    // Replay the whole 1..14 sequence a few more times, LED-only (no
    // repeated side-effecting calls -- every _start() above already ran
    // exactly once, which is all xTaskCreate()/DMA-and-PIO-claim code can
    // tolerate), before handing off to vTaskStartScheduler(). This only
    // ever runs if boot genuinely reached this line with nothing hung or
    // fatal above it -- a real dead-board investigation never reaches this
    // loop at all, which is itself useful information (see
    // docs/BENCH_RUNBOOK.md section 1.3: "if it never repeats, it never
    // finished booting"). The point is purely to let a bench operator who
    // glanced away mid-sequence, or who wants to double check a stage
    // count, watch the full 1..14 run again without a fresh power cycle --
    // "run the full instrumented sequence, and only then proceed to
    // vTaskStartScheduler()" is deliberately satisfied by replaying complete
    // passes here rather than looping forever (which would never start the
    // scheduler at all) or re-running any of the real boot work above a
    // second time (which would double-create tasks and double-claim DMA/PIO
    // resources).
    printf("[boot] all 14 stages reached -- replaying beacon sequence %u more time(s) before vTaskStartScheduler()\r\n",
           SIMFW_BOOT_BEACON_REPLAY_COUNT);
    fflush(stdout);
    for (uint32_t replay = 0; replay < SIMFW_BOOT_BEACON_REPLAY_COUNT; replay++) {
        for (uint32_t stage = 1; stage <= SIMFW_BOOT_BEACON_STAGE_COUNT; stage++) {
            simfw_boot_beacon(stage);
        }
    }

    printf("[boot] all tasks started, calling vTaskStartScheduler()\r\n");
    fflush(stdout);
    vTaskStartScheduler();

    // vTaskStartScheduler() does not return on success. Reaching here means
    // scheduler start itself failed (e.g. out of heap for the idle/timer
    // tasks).
    printf("[boot] vTaskStartScheduler() RETURNED -- this should never happen; "
           "scheduler start itself failed (out of heap for idle/timer tasks?)\r\n");
    fflush(stdout);
    for (;;) {
        tight_loop_contents();
    }
}
