#ifndef SAFTYFW_TEST_STUB_BUILD_INFO_H
#define SAFTYFW_TEST_STUB_BUILD_INFO_H
#define SAFTYFW_BUILD_DATE "Jan  1 2026"
#define SAFTYFW_BUILD_TIME "00:00:00"
#define SAFTYFW_BUILD_SIM_PLANT_HONORED 0
#endif
