# worktree_mint.ps1 -- mint or remove a short-lived, collision-proof git
# worktree at origin/dev (default; -Base overrides) under C:\wt\.
#
# WHY THIS EXISTS. The shared main tree at C:\Users\...\kilnCtl normally
# carries somewhere around a hundred dirty tracked paths belonging to other
# concurrent sessions (see CLAUDE.md's "concurrent sessions" notes), so
# nearly all real work has to happen in a separate worktree checked out at
# origin/dev (or -Base <ref>). Two constraints have bitten repeatedly enough to be written
# down as project memory:
#
#   - SHORT PATH. SaftyFW host-test builds overflow the MSVC command line
#     from the default `.claude/worktrees/...` path (nested several levels
#     under a long project directory). The standing convention is a short
#     path directly under `C:\wt\`.
#   - UNIQUE NAME. `C:\wt\` is a flat namespace shared by every concurrent
#     session on this machine (as of 2026-09-16 it holds several hundred
#     entries from past sessions -- see its directory listing). A generic
#     name like `C:\wt\build` or `C:\wt\work` collides with another live
#     session's worktree. This script appends a random suffix to whatever
#     label the caller supplies so a collision is astronomically unlikely,
#     and it refuses outright if the resulting path already exists rather
#     than silently reusing (and corrupting) someone else's worktree.
#
# USAGE
#   powershell -ExecutionPolicy Bypass -File tools\worktree_mint.ps1 -Label myfeature
#       Fetches origin, creates C:\wt\myfeature_<6-char-random> checked out
#       at -Base (default origin/dev; e.g. -Base origin/main) detached, and prints the path on its own line
#       prefixed "WORKTREE: " so a caller can grep it out reliably.
#
#   powershell -ExecutionPolicy Bypass -File tools\worktree_mint.ps1 -Label myfeature -NoSubmodules
#       Same, but skips `git submodule update --init --recursive` (lvgl,
#       mykicadMcp, TFT35-SPI). Use only when the check suite / KilnFW build
#       is not needed -- see the "SUBMODULES A FRESH WORKTREE NEEDS" note
#       below for what breaks without them.
#
#   powershell -ExecutionPolicy Bypass -File tools\worktree_mint.ps1 -Label myfeature -RunSetup
#       Same, then also runs tools\setup.ps1 inside the new worktree. A
#       freshly minted worktree has no tools\PcTools\.venv (gitignored,
#       generated by setup.ps1), so tools\run_all_checks.ps1's PC-side
#       selfcheck fails closed before reaching any gate -- this switch closes
#       that gap so the minted worktree can actually run the full check
#       suite. A setup failure is printed loudly (SETUP: FAILED) but does not
#       fail the mint itself, since the checkout already succeeded.
#
#   powershell -ExecutionPolicy Bypass -File tools\worktree_mint.ps1 -Remove -Path C:\wt\myfeature_ab12cd
#       Removes a worktree cleanly (git worktree remove), but refuses if it
#       has uncommitted changes (tracked modifications, staged changes, or
#       untracked files) -- exactly the situation where a careless remove
#       would silently discard real work.  Pass -Force together with
#       -Remove only when you have already confirmed (by hand) that the
#       dirty state is disposable; the script never assumes that on its own.
#
# EXIT CODES follow this repo's check_*.ps1 convention where applicable:
#   0 -- success (mint: worktree created; remove: worktree removed)
#   1 -- failure (bad args, git error, refused due to dirty state or an
#        already-existing target path)
#
# This is a workflow helper, not a repo-health guard, so it is not wired
# into run_all_checks.ps1 -- there is nothing here for that runner to
# assert about the repository itself.

[CmdletBinding()]
param(
    [string]$Label,
    [switch]$Remove,
    [string]$Path,
    [switch]$Force,
    [string]$WtRoot = "C:\wt",
    [switch]$RunSetup,
    [switch]$NoSubmodules,
    [string]$Base = "origin/dev"
)

# SUBMODULES A FRESH WORKTREE NEEDS (2026-09-19). `git worktree add` does NOT
# initialise submodules -- each submodule path stays an empty directory until
# something runs `git submodule update --init`. Two agents reported today
# that a fresh worktree from this script therefore fails the very checks it
# exists to let them run:
#   * firmware/KilnFW/components/lvgl -- required by every KilnFW target
#     build (check_00_kilnfw_target_build.ps1 / _recovery_ variant); without
#     it CMake fails with "Failed to resolve component 'lvgl'".
#   * tools/mykicadMcp -- required by check_mcp_facade_coverage.ps1 and
#     check_mykicad_golden_suite_runs.ps1.
# The third registered submodule, parts/TFT35-SPI (hardware/mainBoard/parts/
# TFT35-SPI), is reference vendor data for a KiCad footprint, not consumed by
# any check_*.ps1 in the standing suite -- included anyway via --recursive
# below since it costs little and a caller doing hardware work may want it
# populated too.
#
# `--recursive` in case either submodule nests its own (lvgl in particular
# has had submodules of its own upstream). `-NoSubmodules` opts back out for
# a caller who wants a bare checkout fast and does not need the check suite
# to pass -- the mint itself never fails because of this step; a submodule
# init failure is printed loudly but the worktree that was already created
# is still handed back.

# NOTE: deliberately "Continue", not "Stop". PowerShell 5.1 treats a native
# command's stderr output as a terminating NativeCommandError under
# $ErrorActionPreference="Stop" even when the command's exit code is 0 --
# `git fetch`'s ordinary progress banner goes to stderr, so "Stop" here
# would abort this script on a successful fetch. Every git call below is
# checked via $LASTEXITCODE explicitly instead, which is the only reliable
# success signal for a native command in PowerShell 5.1 (see docs/MCP_SERVERS.md
# on the same trap in flash_firmware()'s callers, and tools/push_verify.ps1).
$ErrorActionPreference = "Continue"

function Get-RepoRoot {
    $top = git rev-parse --show-toplevel 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $top) {
        throw "Not inside a git repository (git rev-parse --show-toplevel failed)."
    }
    # git prints forward slashes even on Windows; normalize.
    return ($top -replace '/', '\')
}

function New-RandomSuffix {
    # 6 lowercase-alnum chars -- enough entropy that two concurrent sessions
    # picking the same human label will not also pick the same suffix.
    $chars = "abcdefghijklmnopqrstuvwxyz0123456789".ToCharArray()
    -join (1..6 | ForEach-Object { $chars | Get-Random })
}

if ($Remove) {
    if (-not $Path) {
        Write-Host "ERROR: -Remove requires -Path <worktree directory>." -ForegroundColor Red
        exit 1
    }
    $repoRoot = Get-RepoRoot
    # F14: resolve against PowerShell's location (not the process cwd), literal paths only.
    if (-not (Test-Path -LiteralPath $Path)) {
        Write-Host "ERROR: '$Path' does not exist -- nothing to remove." -ForegroundColor Red
        exit 1
    }
    $full = (Resolve-Path -LiteralPath $Path).ProviderPath.TrimEnd('\')
    # F14: git must confirm this is a LINKED worktree (not the main tree) before anything is touched.
    $isLinked = $false
    $wtLines = git -C $repoRoot worktree list --porcelain 2>$null
    $idx = 0
    foreach ($ln in $wtLines) {
        if ($ln -like 'worktree *') {
            $wp = ($ln.Substring(9) -replace '/', '\').TrimEnd('\')
            if ($idx -gt 0 -and [string]::Equals($wp, $full, [StringComparison]::OrdinalIgnoreCase)) { $isLinked = $true }
            $idx++
        }
    }
    if (-not $isLinked) {
        Write-Host "ERROR: '$full' is not a linked worktree of this repository (git worktree list); refusing." -ForegroundColor Red
        exit 1
    }

    # Refuse on uncommitted changes: tracked modifications/staged changes
    # (git status --porcelain) OR untracked files, unless -Force.
    $porcelain = git -C $full status --porcelain --untracked-files=all 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: '$full' does not look like a git worktree (git status failed)." -ForegroundColor Red
        exit 1
    }
    if ($porcelain -and -not $Force) {
        Write-Host "REFUSED: worktree '$full' has uncommitted changes:" -ForegroundColor Red
        Write-Host $porcelain
        Write-Host "Commit, discard by hand, or pass -Force only after you have reviewed the above." -ForegroundColor Red
        exit 1
    }
    if ($porcelain -and $Force) {
        Write-Host "WARNING: removing '$full' with uncommitted changes present (-Force):" -ForegroundColor Yellow
        Write-Host $porcelain
    }

    # F4: a detached worktree's unlanded commits die with its reflog. Refuse unless -Force.
    $unlanded = @(git -C $full rev-list HEAD --not --remotes --branches 2>$null)
    if ($unlanded.Count -gt 0) {
        Write-Host "commits reachable only from this worktree ($($unlanded.Count)):" -ForegroundColor Yellow
        $unlanded | ForEach-Object { Write-Host "  $_" }
        if (-not $Force) {
            Write-Host "REFUSED: worktree '$full' holds commits that exist nowhere else. Push or branch them, or pass -Force to drop them." -ForegroundColor Red
            exit 1
        }
        Write-Host "WARNING: dropping the commits above (-Force)." -ForegroundColor Yellow
    }

    # Strip junctions/symlinks (e.g. a .venv junction into the main tree) as links
    # BEFORE git recurses; see tools\lib_safe_remove.ps1 for the 2026-10-07 incident.
    . (Join-Path $PSScriptRoot "lib_safe_remove.ps1")
    foreach ($l in (Remove-ReparsePointsUnder -Path $full)) { Write-Host "unlinked reparse point (target untouched): $l" }
    git -C $repoRoot worktree remove $full --force *>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: git worktree remove failed for '$full'." -ForegroundColor Red
        exit 1
    }
    Write-Host "REMOVED: $full" -ForegroundColor Green
    exit 0
}

# --- mint path ---
if (-not $Label) {
    Write-Host "ERROR: -Label <short-name> is required to mint a worktree (e.g. -Label pushcheck)." -ForegroundColor Red
    exit 1
}
if ($Label -notmatch '^[A-Za-z0-9_-]+$') {
    Write-Host "ERROR: -Label must be alphanumeric/underscore/hyphen only (got '$Label')." -ForegroundColor Red
    exit 1
}

$repoRoot = Get-RepoRoot

if (-not (Test-Path $WtRoot)) {
    New-Item -ItemType Directory -Path $WtRoot -Force | Out-Null
}

git fetch origin *>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: git fetch origin failed." -ForegroundColor Red
    exit 1
}

if (-not $Remove) { git -C $repoRoot rev-parse --verify --quiet "$Base^{commit}" *>$null; if ($LASTEXITCODE -ne 0) { Write-Host "ERROR: -Base ref '$Base' does not resolve to a commit." -ForegroundColor Red; exit 1 } }

# Try a handful of times in the (very unlikely) event of a suffix collision
# against another concurrent mint.
$target = $null
for ($i = 0; $i -lt 20; $i++) {
    $candidate = Join-Path $WtRoot ("{0}_{1}" -f $Label, (New-RandomSuffix))
    if (-not (Test-Path $candidate)) {
        $target = $candidate
        break
    }
}
if (-not $target) {
    Write-Host "ERROR: could not find a free worktree path under $WtRoot after 20 attempts." -ForegroundColor Red
    exit 1
}

# Belt-and-suspenders: refuse rather than reuse if somehow the path appeared
# between the check above and here (race with another mint).
if (Test-Path $target) {
    Write-Host "ERROR: '$target' already exists -- refusing to reuse an existing directory." -ForegroundColor Red
    exit 1
}

git -C $repoRoot worktree add --detach $target $Base *>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: git worktree add failed for '$target'." -ForegroundColor Red
    exit 1
}

if (-not $NoSubmodules) {
    Write-Host "Initializing submodules in $target (git submodule update --init --recursive) ..." -ForegroundColor Cyan
    git -C $target submodule update --init --recursive *>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "WARNING: git submodule update --init --recursive failed (exit $LASTEXITCODE) in $target -- KilnFW target builds and mykicadMcp-dependent checks will fail until this is resolved by hand (e.g. re-run: git -C `"$target`" submodule update --init --recursive). The worktree itself was created successfully; this does not fail the mint." -ForegroundColor Yellow
    } else {
        Write-Host "Submodules initialized." -ForegroundColor Green
    }
} else {
    Write-Host "Skipping submodule initialization (-NoSubmodules). KilnFW target builds and mykicadMcp-dependent checks will fail until 'git submodule update --init --recursive' is run by hand in $target." -ForegroundColor Yellow
}

Write-Host "WORKTREE: $target" -ForegroundColor Green

if ($RunSetup) {
    $setupScript = Join-Path $target "tools\setup.ps1"
    if (-not (Test-Path $setupScript)) {
        Write-Host "SETUP: FAILED (tools\setup.ps1 not found at $setupScript)" -ForegroundColor Red
        exit 0
    }
    Write-Host "Running tools\setup.ps1 in $target ..." -ForegroundColor Cyan
    powershell -ExecutionPolicy Bypass -File $setupScript
    if ($LASTEXITCODE -ne 0) {
        Write-Host "SETUP: FAILED (tools\setup.ps1 exited $LASTEXITCODE)" -ForegroundColor Red
        exit 0
    }
    Write-Host "SETUP: ok" -ForegroundColor Green
}

exit 0
